### ISSUE TITLE
Port WPF-based helper GUIs to Avalonia for Mac/Linux

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#136]
We currently do not have any GUI for Bitbucket and GitHub on macOS (and Linux) and require a TTY be present and available. 

IDEs and other graphical-only tools that shell out to `git` will either hang (if they fail to set `GIT_TERMINAL_PROMPT` to `0`) or error immediately as there is not TTY available and there are no supported GUI prompts.

The current Windows-only GUIs for Bitbucket and GitHub are written in WPF/XAML. We should be able to port these to Avalonia with minimal effort and get Mac and Linux GUIs "for free".

**Comment by mminns** [comment]
If it is any help to bootstrap this update here is a prototype I built
https://github.com/itofinity/Atlassian-Authentication-Helper
