### ISSUE TITLE
`fatal:invalid URI: failed to parse host name.` when access an repository with port in url

### ISSUE THREAD

**Issue by yyjdelete** [microsoft/Git-Credential-Manager-Core#156]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.
>Git Credential Manager version 2.0.194-beta+819e6bc120 (Windows, .NET Framework 4.0.30319.42000)
>git version 2.28.0.windows.1

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [x] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**
It need to be an repo needed auth(or test push instead?)

From a terminal, run `git remote -v` to see your remote URL.
>https://github.com:443/yyjdelete/zzzz
or any other private repository with non-default port (http or https), the above one with 443 is just used as an quick test.

* [ ] Yes
* [ ] No, I get a permission error
* [x] No, for a different reason - please describe

When I try to access an repository with port in url which need auth , I see an new fatal shown after update to git-for-windows 2.28 and switch to GCM-Core(with `credential.helper=manager-core`)

---

**Expected behavior**

No `fatal` message should be shown.

**Actual behavior**

>fatal:invalid URI: failed to parse host name.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.
```
git clone https://github.com:443/yyjdelete/zzzz 3
16:58:07.131533 exec-cmd.c:237          trace: resolved executable dir: D:/Tools/Git/mingw64/bin
16:58:07.133519 git.c:444               trace: built-in: git clone https://github.com:443/yyjdelete/zzzz 3
Cloning into '3'...
16:58:07.152508 run-command.c:663       trace: run_command: git remote-https origin https://github.com:443/yyjdelete/zzzz
16:58:07.176495 exec-cmd.c:237          trace: resolved executable dir: D:/Tools/Git/mingw64/libexec/git-core
16:58:07.177511 git.c:704               trace: exec: git-remote-https origin https://github.com:443/yyjdelete/zzzz
16:58:07.177511 run-command.c:663       trace: run_command: git-remote-https origin https://github.com:443/yyjdelete/zzzz
16:58:07.196501 exec-cmd.c:237          trace: resolved executable dir: D:/Tools/Git/mingw64/libexec/git-core
16:58:08.975515 run-command.c:663       trace: run_command: 'git credential-manager-core get'
16:58:09.046435 exec-cmd.c:237          trace: resolved executable dir: D:/Tools/Git/mingw64/libexec/git-core
16:58:09.048434 git.c:704               trace: exec: git-credential-manager-core get
16:58:09.048434 run-command.c:663       trace: run_command: git-credential-manager-core get
16:58:09.101391 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.194-beta+819e6bc120 (Windows, .NET Framework 4.0.30319.42000) 'get'
16:58:09.104401 ...\Command.cs:63       trace: [ExecuteAsync] Start 'get' command...
fatal: 无效的 URI: 未能分析主机名。
16:58:09.149363 run-command.c:663       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://github.com:443': git
```

***UPDATED***:
Looks like the same as https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/271 in old GCM(non-core version)

**Comment by artumino** [comment]
This also affects usernames with domains like emails (which are supported by GitLab).

Also addressed in the old GCM microsoft/Git-Credential-Manager-for-Windows#587

**Comment by mjcheetham** [comment]
Hi @yyjdelete!

We've got a pre-release out now which should allow for port numbers in the remote URL.

https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.246-beta

It's set as a pre-release at the moment and not yet bundled with Git for Windows, and not released on Homebrew for macOS. You can try it out now by manually installing the `.exe` on Windows, if you'd like.

**Comment by mjcheetham** [comment]
Closing this issue now that the a release is available with this fix.
https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.252-beta
