### ISSUE TITLE
Linux: Nerdbank.GitVersioning relies on old libssl

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/Git-Credential-Manager-Core#168]
The `Nerdbank.GitVersioning` package we use for computing versions relies on `libgit2`. It includes a compiled binary that relies on `libssl.so.1.0.0`, which is no longer being packaged in unstable versions of Debian. This is breaking for some testers, but also it will start breaking for more users in future Linux versions.

Here are a few potential fixes:

1. Update `Nerdbank.GitVersioning` to a new version (if available)
2. Replace the package with another way to compute version information.
3. Contribute a fix to `Nerdbank.GitVersioning` to use a new `libgit2` version.

cc: @mjcheetham for his thoughts here.

**Comment by derrickstolee** [comment]
The root-cause might be related [to this line in the platform-choice option](https://github.com/dotnet/Nerdbank.GitVersioning/blob/0abc7985c28e4f62bea65673ce044a885e0daf4c/src/Nerdbank.GitVersioning.Tasks/RuntimeIdMap.cs#L171).

**Comment by mjcheetham** [comment]
If we can avoid using Nerdbank, but _still keep all the goodness_ in the auto versioning etc I'm happy to drop it.

**Comment by derrickstolee** [comment]
> If we can avoid using Nerdbank, but _still keep all the goodness_ in the auto versioning etc I'm happy to drop it.

I'm hoping we can keep the good versioning. But also: Nerdbank doesn't work with partial clones! It would be nice to enable that in our build system.

**Comment by derrickstolee** [comment]
We appear to have gotten around this now that we have a `.deb`. If anyone else tries to compile GCM Core from source and hits this issue, then we can reopen.
