### ISSUE TITLE
git-credential-manager-core configure: bad modification

### ISSUE THREAD

**Issue by jglick** [microsoft/Git-Credential-Manager-Core#177]
I installed https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.246-beta/gcmcore-linux_amd64.2.0.246.34937.deb (Ubuntu 20.04) and ran

```console
$ git-credential-manager-core configure
Configuring component 'Git Credential Manager'...
Configuring component 'Azure Repos provider'...
```

Setting aside the dev.azure.com change, which I do not care about, this changed my `~/.gitconfig` in an odd way:

```diff
 [credential]
-	helper = store
+	helper = 
+	helper = manager-core
```

Note the blank entry. I would have expected

```diff
 [credential]
-	helper = store
+	helper = manager-core
```

**Comment by jglick** [comment]
Really I would have expected

```ini
[credential]
	helper = git-credential-manager-core
	credentialStore = secretservice
```

as an initial default suitable for ordinary use; or at least for `configure` to have prompted me with the options.

**Comment by mjcheetham** [comment]
Hello @jglick, thanks for this!

The blank entry is used to "reset" the list of `helper` values set so far, and then add `manager-core` so it's the first in the list of `helper`s. Unlike other config entries, `credential.helper` is multi-valued and _all_ listed helpers are consulted, in order (from `--system`, to `--global`/`~/.gitconfig`, to `--local`/`.git/config`) until one of them responds with a credential, or writes `quit=1` to stdout.

On Windows and macOS, there is usually a helper set at the `--system` level (`manager`/`wincred`, or `osxkeychain`) that we'd like to override, on a per user basis. The `osxkeychain` also has a habit of responding to every call it gets, and not necessarily doing the correct thing.

On Linux, it's unlikely a `helper` has been set, so perhaps we need more though and about how to handle setting GCM Core as the `credential.helper`.

You can also call `git-credential-manager-core configure --system` to write to the `/etc/gitconfig` file (`--system` level) instead, which default requires root/`sudo`.

Perhaps we need `configure` to review the current settings and prompt the user what they'd like to do (set this per user, or set the system config (if set), etc). I'll re-purpose this issue for tracking such an enhancement to `configure`.

**Comment by mjcheetham** [comment]
Hi @jglick,

We have updated the behaviour of the `configure [--system]` commands to now perform the following update to your `~/.gitconfig` (or `/etc/gitconfig` if used with `--system`):

```diff
 [credential]
     helper = <existing-entry>
+    helper = 
+    helper = <absolute-path-to-GCM>
```

Any existing `credential.helper` entries will be preserved, and GCM (now the full path to the binary) will be added to the multi-var at the end. We still include the 'empty' entry before the GCM entry to make GCM Core the 'exclusive' helper.

Similarly `unconfigure [--system]` will remove the GCM entry, and the 'empty' entry _if no other helpers are present after GCM_.

```diff
 [credential]
     helper = <existing-entry>
-    helper = 
-    helper = <absolute-path-to-GCM>
```

If other entries are present after GCM, we don't remove the empty entry.

```diff
 [credential]
     helper = <existing-entry>
     helper = 
-    helper = <absolute-path-to-GCM>
     helper = <other-entry>
```

---

Note that we still don't set or prompt to select a credential store on Linux. This is tracked here: https://github.com/microsoft/Git-Credential-Manager-Core/issues/209

**Comment by vtbassmatt** [comment]
This looks complete to me, so I'm closing the issue. Feel free to chime in if I've misunderstood.
