### ISSUE TITLE
FAQ doesn't clarify compatibility with SSH

### ISSUE THREAD

**Issue by PeterConstable** [microsoft/Git-Credential-Manager-Core#191]
The answer given for the question ["I want to use SSH"](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/faq.md#q-i-want-to-use-ssh) is to see external documentation. If someone is currently using SSH or knows they need to use SSH in some case, but they're not an expert in authentication mechanisms, a basic question on installing git or a git update will be, "If I choose Git Credential Manager Core, will that mean that SSH authentication will stop working?"

I'm in that situation: I need to authenticate to GitHub repos using two different accounts, and the only way I've managed to make that work has been to configure SSH authentication. But now on installing the Git 2.29.0 update, I'm being pushed strongly toward using Credential Manager Core. I'm left guessing (hoping) that SSH will still work. The FAQ should have clarified that for me.

**Comment by mjcheetham** [comment]
I've updated the FAQs to address your concerns here 😁 
SSH is here to stay, and GCM Core is only useful for people who want to use HTTP(S)-based remotes and need seamless authentication with the major hosting providers.
