### ISSUE TITLE
Is it possible to get a MSI aswell?

### ISSUE THREAD

**Issue by verzada** [microsoft/Git-Credential-Manager-Core#192]
**Feature description**

We use chocolatey to install most of our software via an admin user. An MSI makes it easier to install for all users on a given computer since a normal user will not have access to install the software him/herself. 

A MSI has known arguments which can be used (such as /ALLUSERS) and make sure that the software installed, is installed for all users on a given computer. An exe installation, needs to have the parameters documented by the creator instead of relying on the standard.

**Comment by mjcheetham** [comment]
@verzada thanks for your interest in GCM Core!

The preferred way to install GCM Core on Windows is to get it via the Git for Windows installer (we are now bundled and enabled by default from Git version 2.29).

Is there a particular reason you wish to install GCM Core standalone from Git for Windows?

**Comment by verzada** [comment]
Ah, I didn’t know it was bundled with Git 😅

/Harald

**Comment by vtbassmatt** [comment]
Glad to hear that you're in a good spot with respect to an MSI of GCM Core. I'll close out this issue.

Requests for Git for Windows enhancements can go [here](https://github.com/git-for-windows/git/issues).
