### ISSUE TITLE
Support FIDO and features like Windows Hello

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#211]
This is a tracking issue for MSAL's feature work to add support for "WAM" (that would enable things like Windows Hello directly without needing to use the system browser).

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2124
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2125
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2126
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1339

**Comment by vtbassmatt** [comment]
This is also dependent on https://github.com/microsoft/Git-Credential-Manager-Core/issues/47 I believe.
