### ISSUE TITLE
Make gitHubAuthModes domain specific

### ISSUE THREAD

**Issue by AlexanderLanin** [microsoft/Git-Credential-Manager-Core#223]
gitHubAuthModes is currently a global setting and not specific to single domains. While this usually doesn't matter much, the use case is having an enterprise server which doesn't support OAuth. So I'm setting this to basic. However this will also disable OAuth on github.com. No way to be more specific.
I cannot just set to "basic oauth" as oauth fails in a very non obvious way with a 404 error message.

```
[credential "github.mycompany.com"]
	provider = GitHub
[credential]
	gitHubAuthModes = basic
```

This is a separate feature, but for the full set see #222 and #219.

**Comment by mjcheetham** [comment]
All GCM settings should respect any URL-based scoping, such as `credential.github.mycompany.com.gitHubAuthModes` already.

Are you finding this isn't working?

**Comment by AlexanderLanin** [comment]
You are correct sorry, I must have done something else wrong before.

Works fine:
```
[credential "github.mycompany.com"]
	provider = GitHub
	gitHubAuthModes = basic
```

**Comment by AlexanderLanin** [comment]
Sorry I did it wrong on the second attempt. First one was correct. I accidentally had the gitHubAuthModes config redundantly in system config.

This does not force basic auth mode:

```
[credential "github.mycompany.com"]
	provider = GitHub
	gitHubAuthModes = basic
```

It results in `07:55:14.253544 ...bHostProvider.cs:213 trace: [GetSupportedAuthenticationModesAsync] GitHub Enterprise instance has version '2.21.10' and supports authentication schemes: None
fatal: Must specify at least one AuthenticationModes`

**Comment by mjcheetham** [comment]
Ahh.. my apologies @AlexanderLanin! I've just uncovered a bug in how to search/match the "scope" for credentials!
We are supposed to take a remote URL like `https://sub.example.com/path/here` and search for the following:

```
section.https://sub.example.com/path/here.property
section.sub.example.com/path/here.property
section.https://sub.example.com/path.property
section.sub.example.com/path.property
section.https://sub.example.com.property
section.sub.example.com.property
section.https://example.com.property
section.example.com.property
```

..but for some reason we're not enumerating the 'protocol-less' options. Can you try putting `http://` or `https://` in the configuration as a workaround?

I.e.,

```
git config credential.https://github.mycompany.com.gitHubAuthModes basic
```

I'll investigate why we aren't matching the protocol-less options.

**Comment by mjcheetham** [comment]
I was wrong.. actually the issue is to do with case sensitivity! Drat.

Looks like Git is partially sensitive when matching config keys! That is to say that the `section` and `property` parts are insensitive, but the inner `scope` part _IS_ sensitive!

`section.sCoPE.property != section.scope.property`, but `SECTION.scope.PROPERTY == sEcTiOn.scope.pRoPeRtY`

🤦‍♂️

**Comment by mjcheetham** [comment]
Ah shoot. yes.. In the code we're trying to match against `gitHubAuthModes` but Git is returning to us `githubauthmodes` and we're not matching correctly.
