### ISSUE TITLE
Mac OS Package Installer fails: “cannot check it for malicious software"

### ISSUE THREAD

**Issue by paladinsoft** [microsoft/Git-Credential-Manager-Core#225]
Having problems with brew install so tried package installer. Upon opening installer get "“gcmcore-osx-2.0.280.19487.pkg” can’t be opened because Apple cannot check it for malicious software."

**Comment by mjcheetham** [comment]
This is due to the lack of Apple Notarization. We identified some issues with our build process and the build flags of the .NET Runtime itself.

Closing this as a duplicate of #108
