### ISSUE TITLE
Configurable OAuth ID & Secret

### ISSUE THREAD

**Issue by AlexanderLanin** [microsoft/Git-Credential-Manager-Core#232]
At the moment GitHub Enterprise Server (GHES) does not contain any kind of preconfigured GCM support. It's also not possible to create a new OAuth App with a predefined id/secret. I'm also not aware of any plans of GitHub to change this. So the only thing left is making GCMs id/secret configurable.

I know it's strange/terrible, but that's the only short term solution to make GCM OAuth work on GHES. I've already tried with a modified hardcoded change of those two strings and it does work fine with a GHES/SAML instance.

Next up I would like to suggest to merge id & secret into one entry. Let's say gcm_oauth_identity. Because of two reasons:
* It would take a single line of config-code to make GCM work with GHES. There is a huge difference between "single line" and "here is a config you need to apply".
* I really really REALLY don't want to explain to even 1% of our users why we share some "secret" which is publicly available on our wiki. Compare #228. Not even mentioning some security departments. In the end they will not allow it.

**Comment by mjcheetham** [comment]
Hi @AlexanderLanin,

There is currently already a way to do this (switch the official GitHub OAuth client ID and secret with another one) built-in to GCM Core. See these intentionally undocumented Git [configuration entry constants](https://github.com/microsoft/Git-Credential-Manager-Core/blob/ef29f9adf57abac337a00169fe85b57dcad884e7/src/shared/GitHub/GitHubConstants.cs#L66-L68), or [environment variables](https://github.com/microsoft/Git-Credential-Manager-Core/blob/ef29f9adf57abac337a00169fe85b57dcad884e7/src/shared/GitHub/GitHubConstants.cs#L55-L57).

---

:warning: **WARNING** :warning:

This is a _developer-only_ feature and has **zero support** and is likely to change **without notice**.

---

We strongly recommend against relying on these settings working or existing in the long term, and it is unlikely we'll support something like this in a more permanent fashion.

Regarding more official support for GHES and GCM Core via OAuth, we have nothing to share at this moment, but it is something we might be able to explore.

Right now, the only supported way is to use basic authentication (where enabled), or a personal access token as the "password" field after forcing basic auth to be displayed via [credential.gitHubAuthModes](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/configuration.md#credentialgithubauthmodes]) (current [issues](https://github.com/microsoft/Git-Credential-Manager-Core/issues/223) not-withstanding).

Shall I keep this issue open and repurpose it to track exploration of official GCM Core + GHES support via OAuth?

**Comment by AlexanderLanin** [comment]
Unfortunately in a GHES/SAML context password authentication is disabled and PAT [doesn't work](https://github.com/microsoft/Git-Credential-Manager-Core/issues/222#issuecomment-731842935). So this unsupported OAuth login is the only one that works 🤣 

I would love official support, I recently talked to @Allie about that as well.
Tracking that in a new ticket seems better, since what was proposed here is actually already implemented.

**Comment by mjcheetham** [comment]
> Tracking that in a new ticket seems better, since what was proposed here is actually already implemented.

Tracking: https://github.com/microsoft/Git-Credential-Manager-Core/issues/235
