### ISSUE TITLE
Sourcetree with github

### ISSUE THREAD

**Issue by pragpete** [microsoft/Git-Credential-Manager-Core#238]
I use sourcetree with github. It worked fine with github until the recent auth change. Now it doesn't work. Everytime I push or pull I get a login dialog, which I have to manually fill in because my password manager (Lastpass) does not work with the sourcetree dialogs.

You will probably say it's a problem with sourcetree. But sourcetree worked fine with github before, so this is an issue github should help with.

Please provide clear instructions how to make github work with sourcetree.

**Comment by mjcheetham** [comment]
Hello @pragpete,

Please can you answer the following questions/run the following commands, so we can diagnose what's going on:

- From a terminal, run `git remote -v` to show your remote URL.

- Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by pragpete** [comment]
Hi Mathew,
Thanks for replying.

*git remote -v*
GitHub_Git_Test https://github.com/pragpete/GitTest.git (fetch)
GitHub_Git_Test https://github.com/pragpete/GitTest.git (push)

*git push --set-upstream https://github.com/pragpete/GitTest.git
<https://github.com/pragpete/GitTest.git> master*
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 332 bytes | 332.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/pragpete/GitTest.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from '
https://github.com/pragpete/GitTest.git'.

So Git works fine from the command line. But that's not the problem. I want
to use Sourcetree, because that gives me much better visibility of branches
and commits. This is what I get from Sourcetree when I try to push to
GitHub.

*Git Push from Sourcetree*
git -c diff.mnemonicprefix=false -c core.quotepath=false
--no-optional-locks push -v --tags --set-upstream GitHub_Git_Test
master:master
Logon failed, use ctrl+c to cancel basic credential prompt.
Pushing to https://github.com/pragpete/GitTest.git
Completed with errors, see above.


*This is the sequence in SourceTree*
[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]


thanks
Pete

**Comment by mjcheetham** [comment]
> Logon failed, use ctrl+c to cancel basic credential prompt.

Hmm.. this is strange. It looks like Sourcetree is using an old version of GCM (GCM for Windows). That error message comes from GCM for Windows:

https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/master/Cli/Manager/Program.cs#L59

> *This is the sequence in SourceTree*
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

Something went wrong in your reply of images with GitHub - I cannot see them. I assume that these are images of authentication prompts you're getting whilst using SourceTree, and that entering username/password(/2FA code) in these no longer works?

If that's the case, then the reason is that GitHub has removed the username/password-based authentication the older GCM for Windows used to use to create authentication tokens (see [here](https://aka.ms/gcmcore-githubauthchanges)).

The new GCM (GCM Core, this project) supports the new authentication mechanism GitHub now require, however Sourcetree isn't using it.

Can you please set the following environment variables, restart Sourcetree, and then upload the resulting log file?

```
GIT_TRACE=C:\Users\<USERNAME>\gcm.log
GCM_TRACE=C:\Users\<USERNAME>\gcm.log
```

Thanks!

(remember to remove any sensitive information like URLs or user accounts from these logs before posting here)

**Comment by mjcheetham** [comment]
@mminns any idea why Sourcetree would not be using the same credential helper as the command-line invocation of `git` would be?

**Comment by pragpete** [comment]
I set these:

GIT_TRACE=C:\Users\<USERNAME>\gcm.log
GCM_TRACE=C:\Users\<USERNAME>\gcm.log

then restarted SourceTree and I get the attached log

thanks

**Comment by pragpete** [comment]
[gcm.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/5691325/gcm.log)

**Comment by pragpete** [comment]
Here is the sequence of steps in Sourcetree:
![sourcetree_github_1](https://user-images.githubusercontent.com/19496352/102130764-250bd800-3e49-11eb-8dea-3d29ce17c492.png)
![sourcetree_github_2](https://user-images.githubusercontent.com/19496352/102130781-2d641300-3e49-11eb-86be-f7a4cb9f5aa5.png)
![sourcetree_github_3](https://user-images.githubusercontent.com/19496352/102130794-305f0380-3e49-11eb-89c7-edb82673e354.png)
![sourcetree_github_4](https://user-images.githubusercontent.com/19496352/102130802-33f28a80-3e49-11eb-8716-6eb787bc28a8.png)

**Comment by mjcheetham** [comment]
Hi @pragpete,

Can you open Sourcetools and go to: `Tools > Options > Git`, and scroll down to the "Git Version" section. Which version of Git is being used by Sourcetools?

Is it the embedded version, or the system version?

![image](https://user-images.githubusercontent.com/5658207/102606119-2e819280-411e-11eb-89e7-02ce8d659d99.png)
![image](https://user-images.githubusercontent.com/5658207/102606131-32adb000-411e-11eb-9de6-734983c4f5ff.png)

The latest embedded version used by Sourcetools appears to be Git for Windows 2.26.2, which only includes the older, and now deprecated Git Credential Manager for Windows, not GCM Core.

This explains why you're seeing the older GCM4Windows prompts, and not GCM Core.

As to why the older GCM4Windows no longer works with GitHub.. GitHub recently (2020-11-13) changed their authentication mechanisms to remove username/password-based authentication, that GCM4Windows used. See their blog post:
https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/

GCM Core supports OAuth-based authentication which is the requirement from GitHub now. Until Sourcetree is updated to include a later version of it's embedded version of Git (2.26.2 is several releases behind now), I recommend installing Git for Windows standalone, and then set Sourcetools to use the "system version" of Git.

Git for Windows: https://git-scm.com/download/win

**Comment by mjcheetham** [comment]
Looking at the beta programme for Sourcetree, I can see that the 3.4.0-beta-1 version that was announced about a week ago includes Git 2.29.2, which bundles GCM Core. Hopefully once the next release is out you can then go back to using the embedded version of Git they ship.

**Comment by pragpete** [comment]
That was the problem. Sourcetree was set to use its embedded Git, which was the old 2.20.1 version.

![sourcetree](https://user-images.githubusercontent.com/19496352/102608016-2545f500-4121-11eb-992b-096ab18198c8.PNG)

I switched SourceTree to use the system git, and everything works. 

Brilliant. @mjcheetham Thanks very much !

**Comment by mjcheetham** [comment]
You're welcome @pragpete!

**Comment by tmjones212** [comment]
Had the exact same problem, changing to System worked for me too.
