### ISSUE TITLE
Respect `http.sslCAInfo` when set and validate TLS certs against it

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#242]
**Feature description**

GCM Core uses the .NET HTTP stack, which itself uses the native OS crypto stacks (schannel/CNG on Windows, Apple's Security Framework as of .NET Core 2.0, and OpenSSL on Linux).

When using self-signed certificates over HTTPS remotes with Git on Windows or macOS with the default options, the `http.sslCAInfo` option has no effect, since this is only used by OpenSSL.

Currently the only option is for the user to install/trust their certificates in the system store (Windows Certificate Store, or the macOS Keychain) to have GCM allow connections using the certificates (or disable TLS verification outright via `http.sslVerify = false`).

We should be able to use the same extension point we're currently using for the TLS verification disabling to respect the `http.sslCAInfo` setting.

(see: https://github.com/dotnet/announcements/issues/21)

**Comment by dscho** [comment]
If you want to be _fully_ consistent with Git for Windows, you should also ignore `http.sslCAInfo` if `http.backend == "schannel" && (http.schannelUseSSLCAInfo == unset || http.schannelUseSSLCAInfo == "false")`.

**Comment by vtbassmatt** [comment]
@mjcheetham I might be missing something - is there a need to trust a self-signed cert only in GCM Core but not in the system's cert store? The latter feels like the right thing to me.

**Comment by mjcheetham** [comment]
@dscho is it correct that Git supports some special magic values for config paths, like `%PREFIX/` or something?
We should probably also support that in GCM's handling so we match behaviour between GCM and Git.

**Comment by dscho** [comment]
> 
> 
> @dscho is it correct that Git supports some special magic values for config paths, like `%PREFIX/` or something?
> We should probably also support that in GCM's handling so we match behaviour between GCM and Git.

Yes, current Git for Windows [special-cases paths in the config which start with a single `/`](https://github.com/git-for-windows/git/commit/40c063fb720bbee9caaa802e3d48ed51303318f9#diff-dd5e9dc8fe1f52308750c5b22086433b63835d5a70fc1d0b910fba8b1aceb694): They are treated as being relative to the installation location. (It is actually slightly more complicated: if you install Git for Windows into `C:\Program Files\Git`, then `git.exe` will live in `C:\Program Files\Git\mingw64\bin\git.exe` (for 64-bit) and the path is interpreted to be relative to that `mingw64` directory, the "prefix").

However, when upstreaming this as https://github.com/gitgitgadget/git/pull/66, reviewers were pretty opposed to using a simple leading `/` as indicator that this should be interpreted as relative to the prefix, and it will make it into Git as `%(prefix)/` special-casing. Git for Windows will then follow suite by deprecating the leading-`/` special-casing.

**Comment by dscho** [comment]
BTW if there is _any_ chance to let GCM call `git config --type=path http.sslCAInfo`, then GCM won't have to replicate the (slightly convoluted) logic of Git for Windows.

**Comment by mjcheetham** [comment]
> BTW if there is _any_ chance to let GCM call `git config --type=path http.sslCAInfo`, then GCM won't have to replicate the (slightly convoluted) logic of Git for Windows.

I've created this issue to track: https://github.com/microsoft/Git-Credential-Manager-Core/issues/425
