### ISSUE TITLE
Git failed with a fatal error. Failed to write item to store

### ISSUE THREAD

**Issue by suthishnairs** [microsoft/Git-Credential-Manager-Core#245]
When trying to clone GIT repo, getting below error from Visual Studio

> Git failed with a fatal error.
> Failed to write item to store. [0x520]
> A specified logon session does not exist. It may already have been
> terminated
> POST git-upload-pack (214 bytes)
> remote: Azure Repos
> remote: remote:
> Found 3 objects to send (17ms)

Tried in both the versions of Visual Studio Enterprise 2019 16.7 and 16.8.

16.7: Tried to clone multiple times, sometimes all the files gets downloaded but above error still pops up.

16.8: No download or cloning happening, same error.

I tried recreating Azure personal access token, also added an Generic Credentials into Windows Credentials.

Nothing worked, any help here, please.

Using: Visual Studio Enterprise 2019 & Git-2.29.2.2-64-bit

**Comment by mjcheetham** [comment]
Hi @suthishnairs, are you running Visual Studio as a different user? (either via `runas` or, right-click Run as Admin/OtherUser)?

Are you using any other remoting technologies to sign-in to Windows, such as SSH, Remote Desktop, etc?

**Comment by suthishnairs** [comment]
> Hi @suthishnairs, are you running Visual Studio as a different user? (either via `runas` or, right-click Run as Admin/OtherUser)?
> 
> Are you using any other remoting technologies to sign-in to Windows, such as SSH, Remote Desktop, etc?

Hi @mjcheetham, Yes, I ran Visual Studio "Administrator". Actually, am under Administrator privilege's group.
Using SSO (Azure DevOps).

Also, I can clone, pull, push etc. through Git command lines, but not using Visual Studio.

**Comment by vtbassmatt** [comment]
@mjcheetham is this in the GCM Core stack, or is it failing someplace else in Git before it gets to us? (Wondering if we need to get our friends in VS involved.)

**Comment by Nikhilnick1203** [comment]
Hi. 
I'm facing the same issue. Is this issue resolve? If yes, could you please help me out

**Comment by suthishnairs** [comment]
@mjcheetham @vtbassmatt 

If we clone the repo from browser using option "Clone button" and select IDE as "Clone in 
Visual Studio", the repo download will be successful. 
So it seems browser authenticates the VS IDE to download the repo. 

But, if we try to clone directly from VS, the Git authentication window pops up and mentioned error comes.

More seem an authentication or authorization issue.

**Comment by rashtripathy** [comment]
I am facing the same error, each time I try to clone I get the error below:
"Git failed with a fatal error.
Failed to write item to store. [0x520]
A specified logon session does not exist. It may already have been
terminated"


Can anybody help?

**Comment by wicked1133** [comment]
I am using Powershell Remote Session. Enter-PSSession and running 'git clone,fetch or pull' shows the following Error:

```
git : fatal: Failed to enumerate credentials. [0x520]
    + CategoryInfo          : NotSpecified: (fatal: Failed t...ntials. [0x520]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

fatal: A specified logon session does not exist. It may already have been terminated
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://git.swisscom.com': No such file or directory
```

my credentials for the git servers are stored in windows credential manager. The powershell is running with a different credentials.

any idea?

**Comment by SudhansuNayak** [comment]
I am also facing the same error whenever I try to Sync, I tried all option install a new version of git, checked the permission, clone the solution, clear cache  etc. but still no luck. Please suggest.

Git failed with a fatal error.
Git failed with a fatal error.
Failed to write item to store. [0x520]
A specified logon session does not exist. It may already have been terminated

**Comment by nonbob** [comment]
I'm seeing the same thing in a remote PowerShell session.  I thought to might be a two-hop problem and that CredSSP might fix it but. . .no.

**Comment by mjcheetham** [comment]
The latest release supports a DPAPI-based credential store on Windows that should work in these scenario.
Please see [here](https://aka.ms/gcmcore-credstores) for more information on how to change the credential store.

Closing.

**Comment by suthishnairs** [comment]
> The latest release supports a DPAPI-based credential store on Windows that should work in these scenario. Please see [here](https://aka.ms/gcmcore-credstores) for more information on how to change the credential store.
> 
> Closing.

Yes, Thank You, this worked !
