### ISSUE TITLE
SSO Login fails (GIT is using basic login)

### ISSUE THREAD

**Issue by mrkprdo** [microsoft/Git-Credential-Manager-Core#246]
**Which Version of GCM are you using ?**
From a command prompt, run ``git credential-manager version`` and paste the output.

Git Credential Manager for Windows version 1.20.0

**Which service are you trying to connect to**
* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [x] Bitbucket
* [ ] Other? - please describe;

**If AzureDevops Hosted describe your url**
* [ ] dev.azure.com/org
* [ ] org.visualstudio.com

**If you're using Azure DevOps, can you access the repository in the browser via the same URL?**
* [ ] Yes
* [ ] No, I get a permission error.
* [ ] No, for a different reason: 

**If you're using Azure DevOps, and the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**
* [ ] I only see one identity.
* [ ] I checked each and none worked.

**Expected behavior**
A clear and concise description of what you expected to happen (or code).
Running git clone '<repo>'
Opens GCMW and enters email and password
Then clones repo locally

**Actual behavior**
A clear and concise description of what happens, e.g. exception is thrown, UI freezes
fatal: Authentication failed for '<repo>'
From WebUI, logging in to bitbucket redirects me to my company's SSO, before getting access to bitbucket.
Not sure if that has to be the cause of this issue.

**Set the env variables GCM_TRACE=1 and GIT_TRACE=1 and run your git command.  Redact any private information and attach the log**

removed log

**Comment by mjcheetham** [comment]
Hi @mrkprdo, I've transferred this issue to the GCM Core project, since the older GCM for Windows is no longer maintained or supported.

You are in fact already using GCM Core (version 2.x and above is GCM Core).. see this line in your trace output:

```
13:47:53.935942 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.280-beta+1f4c6db90f (Windows, .NET Framework 4.0.30319.42000) 'get'
```

I can see from the trace logs that you're using Bitbucket Server (on-prem). Is this correct?

```
13:47:53.943888 ...\Command.cs:63       trace: [ExecuteAsync] Start 'get' command...
13:47:53.953862 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
13:47:53.954863 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
13:47:53.954863 ...\Command.cs:75       trace: [ExecuteAsync]   host=bitbucket.reqcentral.com
13:47:54.282982 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
13:47:54.285973 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'Generic' was selected.
```

Since GCM doesn't know this is URL is BB Server (`https://bitbucket.reqcentral.com`), you need to tell it explicitly.

If you run the following, you can set `bitbucket.reqcentral.com` as a Bitbucket Server instance:

```batch
git config --global credential.bitbucket.reqcentral.com.provider bitbucket
```

After setting the above config, can you try again? Thanks!
