### ISSUE TITLE
Open world-writable directory /var/tmp/.net

### ISSUE THREAD

**Issue by paulgear** [microsoft/Git-Credential-Manager-Core#247]
Running `git-credential-manager --help` creates `/var/tmp/.net` as a world-writable directory, without adding the sticky bit.  This is flagged as a vulnerability by scanners such as Qualys or the CIS Benchmark.

Given that the directory is owned by the calling user, there seems to be no reason to place it in `/var/tmp` or to make it world writable, but at the very least it should have the sticky bit to reduce the risk of symlink attacks and the like.

**Comment by mjcheetham** [comment]
@paulgear, I assume you are using GCM Core on Linux here, and not macOS or Windows? If so can you tell me what version or release?

Also by `git-credential-manager --help` do you mean `git-credential-manager-core --help`?

This project (GCM Core) uses the executable name `git-credential-manager-core`. The [retired Java-based GCM for macOS and Linux](https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux), and the also retired [classic .NET GCM for Windows](https://github.com/microsoft/Git-Credential-Manager-for-Windows), both use the older `git-credential-manager` executable name.

The `/var/tmp/.net` directory is an artifact of the way we're using the .NET Core runtime and the ['single file' distribution model](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file), and is outside of our direct control (other than not using this distribution/publishing model).

It might be worth [raising this an an issue on the .NET project](https://github.com/dotnet/runtime/issues/new/choose)?

**Comment by paulgear** [comment]
@mjcheetham Apologies, yes - `git-credential-manager-core --help`.  Version is "Git Credential Manager version 2.0.280-beta+1f4c6db90f (Linux, .NET Core 3.1.6)".  Running on Ubuntu 18.04 LTS, although I'm guessing that doesn't really matter.

I'm not sure I could create a coherent bug for .NET Core, since I'm not a C# dev and don't know anything about the single file distribution model.

**Comment by vtbassmatt** [comment]
Moved to the .NET repo: https://github.com/dotnet/runtime/issues/48174

**Comment by vtbassmatt** [comment]
@paulgear it's not clear to me if the .NET team will fix this for .NET 3.1 or not; they confirmed it's addressed in .NET 5.0. Until we're able to upgrade GCM Core to .NET 5, they offered a workaround. You can set [`DOTNET_BUNDLE_EXTRACT_BASE_DIR`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#environment-variables) in the environment to choose where .NET will unzip the bundle.

**Comment by paulgear** [comment]
Thanks @vtbassmatt.  I'm following the other issue you created - thanks very much for following up.

I don't think choosing where the unzip happens will fix anything unless it's also removed once it's finished, which would require changes to the postinstall script for git-credential-manager-core.
