### ISSUE TITLE
git-credential-manager-core: not found

### ISSUE THREAD

**Issue by nipunn1313** [microsoft/Git-Credential-Manager-Core#252]
Hi,

After attempting to install from `.deb` out of the box on linux, I hit this issue:

```
/var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core get: 1: /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core get: /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core: not found
```

I followed the instructions by first installing the dpkg - then running

```
git-credential-manager-core configure
git config --global credential.credentialStore gpg  # same issue regardless of what I select here
```

Other potentially helpful information
```
nipunn@nipunn-desk:~$ git-credential-manager-core --version
Git Credential Manager version 2.0.289-beta+22bd06dc57 (Linux, .NET Core 3.1.10)
nipunn@nipunn-desk:~$ which git-credential-manager-core
/usr/bin/git-credential-manager-core
```

If I manually edit ~/.gitconfig to search for the path `/usr/bin/git-credential-manager-core` instead of the one in /var/tmp, then things work. I suspect this might be an issue with `git-credential-manager-core --configure` Not sure where this /var/tmp is coming from.

I noticed the directory where it searches for git-credential-manager-core is filled with dll's
```
nipunn@nipunn-desk:~$ ls /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu
Atlassian.Bitbucket.dll
createdump
git-credential-manager-core.deps.json
git-credential-manager-core.dll
git-credential-manager-core.runtimeconfig.json
GitHub.dll
libclrjit.so
libcoreclr.so
libcoreclrtraceptprovider.so
libdbgshim.so
libhostfxr.so
libhostpolicy.so
libmscordaccore.so
libmscordbi.so
Microsoft.AzureRepos.dll
Microsoft.CSharp.dll
Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.Binder.dll
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.Configuration.EnvironmentVariables.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Primitives.dll
Microsoft.Git.CredentialManager.dll
Microsoft.Identity.Client.dll
Microsoft.Identity.Client.Extensions.Msal.dll
Microsoft.IdentityModel.JsonWebTokens.dll
Microsoft.IdentityModel.Logging.dll
Microsoft.IdentityModel.Tokens.dll
Microsoft.VisualBasic.Core.dll
Microsoft.VisualBasic.dll
Microsoft.Win32.Primitives.dll
Microsoft.Win32.Registry.dll
mscorlib.dll
netstandard.dll
Newtonsoft.Json.dll
NOTICE
SOS_README.md
System.AppContext.dll
System.Buffers.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.Immutable.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.Annotations.dll
System.ComponentModel.DataAnnotations.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Configuration.dll
System.Console.dll
System.Core.dll
System.Data.Common.dll
System.Data.DataSetExtensions.dll
System.Data.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.dll
System.Drawing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.Globalization.Native.so
System.IO.Compression.Brotli.dll
System.IO.Compression.dll
System.IO.Compression.FileSystem.dll
System.IO.Compression.Native.a
System.IO.Compression.Native.so
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.AccessControl.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.AccessControl.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Memory.dll
System.Native.a
System.Native.so
System.Net.dll
System.Net.Http.dll
System.Net.HttpListener.dll
System.Net.Http.Native.a
System.Net.Http.Native.so
System.Net.Mail.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Security.Native.a
System.Net.Security.Native.so
System.Net.ServicePoint.dll
System.Net.Sockets.dll
System.Net.WebClient.dll
System.Net.WebHeaderCollection.dll
System.Net.WebProxy.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.Numerics.dll
System.Numerics.Vectors.dll
System.ObjectModel.dll
System.Private.CoreLib.dll
System.Private.DataContractSerialization.dll
System.Private.Uri.dll
System.Private.Xml.dll
System.Private.Xml.Linq.dll
System.Reflection.DispatchProxy.dll
System.Reflection.dll
System.Reflection.Emit.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.Extensions.dll
System.Reflection.Metadata.dll
System.Reflection.Primitives.dll
System.Reflection.TypeExtensions.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.InteropServices.WindowsRuntime.dll
System.Runtime.Intrinsics.dll
System.Runtime.Loader.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Runtime.WindowsRuntime.dll
System.Runtime.WindowsRuntime.UI.Xaml.dll
System.Security.AccessControl.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Cng.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Native.OpenSsl.a
System.Security.Cryptography.Native.OpenSsl.so
System.Security.Cryptography.OpenSsl.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.ProtectedData.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.dll
System.Security.Principal.dll
System.Security.Principal.Windows.dll
System.Security.SecureString.dll
System.ServiceModel.Web.dll
System.ServiceProcess.dll
System.Text.Encoding.CodePages.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.Encodings.Web.dll
System.Text.Json.dll
System.Text.RegularExpressions.dll
System.Threading.Channels.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Transactions.dll
System.Transactions.Local.dll
System.ValueTuple.dll
System.Web.dll
System.Web.HttpUtility.dll
System.Windows.dll
System.Xml.dll
System.Xml.Linq.dll
System.Xml.ReaderWriter.dll
System.Xml.Serialization.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
WindowsBase.dll
```

**Comment by kyle-rader** [comment]
That looks like an issue with the configure command setting the path the automatically unpacked tmp location instead of the single-exe deployed by the .deb installer.

Cheers,

Kyle Rader (he/him<https://www.mypronouns.org/what-and-why>)
Microsoft.Office.Engineering.Developer_Platform

**Comment by AndrewLe15** [comment]
> If I manually edit ~/.gitconfig to search for the path /usr/bin/git-credential-manager-core instead of the one in /var/tmp, then things work. 

Thanks for this! I was running into the same issue and resolved with this.

**Comment by GreenRanger-IT** [comment]
> Hi,
> 
> After attempting to install from `.deb` out of the box on linux, I hit this issue:
> 
> ```
> /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core get: 1: /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core get: /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core: not found
> ```
> 
> I followed the instructions by first installing the dpkg - then running
> 
> ```
> git-credential-manager-core configure
> git config --global credential.credentialStore gpg  # same issue regardless of what I select here
> ```
> 
> Other potentially helpful information
> 
> ```
> nipunn@nipunn-desk:~$ git-credential-manager-core --version
> Git Credential Manager version 2.0.289-beta+22bd06dc57 (Linux, .NET Core 3.1.10)
> nipunn@nipunn-desk:~$ which git-credential-manager-core
> /usr/bin/git-credential-manager-core
> ```
> 
> If I manually edit ~/.gitconfig to search for the path `/usr/bin/git-credential-manager-core` instead of the one in /var/tmp, then things work. I suspect this might be an issue with `git-credential-manager-core --configure` Not sure where this /var/tmp is coming from.
> 
> I noticed the directory where it searches for git-credential-manager-core is filled with dll's
> 
> ```
> nipunn@nipunn-desk:~$ ls /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu
> Atlassian.Bitbucket.dll
> createdump
> git-credential-manager-core.deps.json
> git-credential-manager-core.dll
> git-credential-manager-core.runtimeconfig.json
> GitHub.dll
> libclrjit.so
> libcoreclr.so
> libcoreclrtraceptprovider.so
> libdbgshim.so
> libhostfxr.so
> libhostpolicy.so
> libmscordaccore.so
> libmscordbi.so
> Microsoft.AzureRepos.dll
> Microsoft.CSharp.dll
> Microsoft.Extensions.Configuration.Abstractions.dll
> Microsoft.Extensions.Configuration.Binder.dll
> Microsoft.Extensions.Configuration.dll
> Microsoft.Extensions.Configuration.EnvironmentVariables.dll
> Microsoft.Extensions.DependencyInjection.Abstractions.dll
> Microsoft.Extensions.Logging.Abstractions.dll
> Microsoft.Extensions.Logging.dll
> Microsoft.Extensions.Options.dll
> Microsoft.Extensions.Primitives.dll
> Microsoft.Git.CredentialManager.dll
> Microsoft.Identity.Client.dll
> Microsoft.Identity.Client.Extensions.Msal.dll
> Microsoft.IdentityModel.JsonWebTokens.dll
> Microsoft.IdentityModel.Logging.dll
> Microsoft.IdentityModel.Tokens.dll
> Microsoft.VisualBasic.Core.dll
> Microsoft.VisualBasic.dll
> Microsoft.Win32.Primitives.dll
> Microsoft.Win32.Registry.dll
> mscorlib.dll
> netstandard.dll
> Newtonsoft.Json.dll
> NOTICE
> SOS_README.md
> System.AppContext.dll
> System.Buffers.dll
> System.Collections.Concurrent.dll
> System.Collections.dll
> System.Collections.Immutable.dll
> System.Collections.NonGeneric.dll
> System.Collections.Specialized.dll
> System.ComponentModel.Annotations.dll
> System.ComponentModel.DataAnnotations.dll
> System.ComponentModel.dll
> System.ComponentModel.EventBasedAsync.dll
> System.ComponentModel.Primitives.dll
> System.ComponentModel.TypeConverter.dll
> System.Configuration.dll
> System.Console.dll
> System.Core.dll
> System.Data.Common.dll
> System.Data.DataSetExtensions.dll
> System.Data.dll
> System.Diagnostics.Contracts.dll
> System.Diagnostics.Debug.dll
> System.Diagnostics.DiagnosticSource.dll
> System.Diagnostics.FileVersionInfo.dll
> System.Diagnostics.Process.dll
> System.Diagnostics.StackTrace.dll
> System.Diagnostics.TextWriterTraceListener.dll
> System.Diagnostics.Tools.dll
> System.Diagnostics.TraceSource.dll
> System.Diagnostics.Tracing.dll
> System.dll
> System.Drawing.dll
> System.Drawing.Primitives.dll
> System.Dynamic.Runtime.dll
> System.Globalization.Calendars.dll
> System.Globalization.dll
> System.Globalization.Extensions.dll
> System.Globalization.Native.so
> System.IO.Compression.Brotli.dll
> System.IO.Compression.dll
> System.IO.Compression.FileSystem.dll
> System.IO.Compression.Native.a
> System.IO.Compression.Native.so
> System.IO.Compression.ZipFile.dll
> System.IO.dll
> System.IO.FileSystem.AccessControl.dll
> System.IO.FileSystem.dll
> System.IO.FileSystem.DriveInfo.dll
> System.IO.FileSystem.Primitives.dll
> System.IO.FileSystem.Watcher.dll
> System.IO.IsolatedStorage.dll
> System.IO.MemoryMappedFiles.dll
> System.IO.Pipes.AccessControl.dll
> System.IO.Pipes.dll
> System.IO.UnmanagedMemoryStream.dll
> System.Linq.dll
> System.Linq.Expressions.dll
> System.Linq.Parallel.dll
> System.Linq.Queryable.dll
> System.Memory.dll
> System.Native.a
> System.Native.so
> System.Net.dll
> System.Net.Http.dll
> System.Net.HttpListener.dll
> System.Net.Http.Native.a
> System.Net.Http.Native.so
> System.Net.Mail.dll
> System.Net.NameResolution.dll
> System.Net.NetworkInformation.dll
> System.Net.Ping.dll
> System.Net.Primitives.dll
> System.Net.Requests.dll
> System.Net.Security.dll
> System.Net.Security.Native.a
> System.Net.Security.Native.so
> System.Net.ServicePoint.dll
> System.Net.Sockets.dll
> System.Net.WebClient.dll
> System.Net.WebHeaderCollection.dll
> System.Net.WebProxy.dll
> System.Net.WebSockets.Client.dll
> System.Net.WebSockets.dll
> System.Numerics.dll
> System.Numerics.Vectors.dll
> System.ObjectModel.dll
> System.Private.CoreLib.dll
> System.Private.DataContractSerialization.dll
> System.Private.Uri.dll
> System.Private.Xml.dll
> System.Private.Xml.Linq.dll
> System.Reflection.DispatchProxy.dll
> System.Reflection.dll
> System.Reflection.Emit.dll
> System.Reflection.Emit.ILGeneration.dll
> System.Reflection.Emit.Lightweight.dll
> System.Reflection.Extensions.dll
> System.Reflection.Metadata.dll
> System.Reflection.Primitives.dll
> System.Reflection.TypeExtensions.dll
> System.Resources.Reader.dll
> System.Resources.ResourceManager.dll
> System.Resources.Writer.dll
> System.Runtime.CompilerServices.Unsafe.dll
> System.Runtime.CompilerServices.VisualC.dll
> System.Runtime.dll
> System.Runtime.Extensions.dll
> System.Runtime.Handles.dll
> System.Runtime.InteropServices.dll
> System.Runtime.InteropServices.RuntimeInformation.dll
> System.Runtime.InteropServices.WindowsRuntime.dll
> System.Runtime.Intrinsics.dll
> System.Runtime.Loader.dll
> System.Runtime.Numerics.dll
> System.Runtime.Serialization.dll
> System.Runtime.Serialization.Formatters.dll
> System.Runtime.Serialization.Json.dll
> System.Runtime.Serialization.Primitives.dll
> System.Runtime.Serialization.Xml.dll
> System.Runtime.WindowsRuntime.dll
> System.Runtime.WindowsRuntime.UI.Xaml.dll
> System.Security.AccessControl.dll
> System.Security.Claims.dll
> System.Security.Cryptography.Algorithms.dll
> System.Security.Cryptography.Cng.dll
> System.Security.Cryptography.Csp.dll
> System.Security.Cryptography.Encoding.dll
> System.Security.Cryptography.Native.OpenSsl.a
> System.Security.Cryptography.Native.OpenSsl.so
> System.Security.Cryptography.OpenSsl.dll
> System.Security.Cryptography.Primitives.dll
> System.Security.Cryptography.ProtectedData.dll
> System.Security.Cryptography.X509Certificates.dll
> System.Security.dll
> System.Security.Principal.dll
> System.Security.Principal.Windows.dll
> System.Security.SecureString.dll
> System.ServiceModel.Web.dll
> System.ServiceProcess.dll
> System.Text.Encoding.CodePages.dll
> System.Text.Encoding.dll
> System.Text.Encoding.Extensions.dll
> System.Text.Encodings.Web.dll
> System.Text.Json.dll
> System.Text.RegularExpressions.dll
> System.Threading.Channels.dll
> System.Threading.dll
> System.Threading.Overlapped.dll
> System.Threading.Tasks.Dataflow.dll
> System.Threading.Tasks.dll
> System.Threading.Tasks.Extensions.dll
> System.Threading.Tasks.Parallel.dll
> System.Threading.Thread.dll
> System.Threading.ThreadPool.dll
> System.Threading.Timer.dll
> System.Transactions.dll
> System.Transactions.Local.dll
> System.ValueTuple.dll
> System.Web.dll
> System.Web.HttpUtility.dll
> System.Windows.dll
> System.Xml.dll
> System.Xml.Linq.dll
> System.Xml.ReaderWriter.dll
> System.Xml.Serialization.dll
> System.Xml.XDocument.dll
> System.Xml.XmlDocument.dll
> System.Xml.XmlSerializer.dll
> System.Xml.XPath.dll
> System.Xml.XPath.XDocument.dll
> WindowsBase.dll
> ```

Hi, stuck at the same place? have edited the ~/.gitconfig file and works but how do you add your token to the password-store? i put it in a text file in that directly but 'pass init' doesn't seem to re-initialize.

**Comment by GreenRanger-IT** [comment]
Problem fixed now. it was a problem with the gpg key

**Comment by vtbassmatt** [comment]
I think this is an area that Kyle or his designee will be addressing.

**Comment by mjcheetham** [comment]
We've just merged in a change to move to .NET 5 on Linux. The handling of "single-file" .NET applications is much improved, and once this PR is in this should be fixed for the next release:

https://github.com/microsoft/Git-Credential-Manager-Core/pull/298
