### ISSUE TITLE
[Documentation] Does GCM Core do per REPOSITORY/URL or per HOST authentication?

### ISSUE THREAD

**Issue by maddes-b** [microsoft/Git-Credential-Manager-Core#253]
Dear all,

I just updated git on my Windows machine and was informed that I should use GCM Core.
Right now I decided against it, due to a special case I had with GCM for Windows.
Then read the GCM Core documentation, but did not find the information I was looking for or it was just not clearly expressed.

There are multiple repositories on GitHub which I use with different accounts (work vs. private).
With GCM for Windows I could just define `git config --global credential.useHttpPath true` and the full path was always used to get the credential, allowing me to connect with different users to different repositories on the same provider.

Questions:
* Does GCM Core do per REPOSITORY/URL or per HOST authentication by default?
  * Is this configurable? On which levels? Different config for different providers? Examples?
* Enhance documentation.

Kind regards
Maddes

P.S.: The selection of "Authentication failure" and "Feature Request" did not fit my case. I chosed "Auth fail" due to being an auth question and not a feature request (which it may become depending on the answer).

**Comment by mjcheetham** [comment]
Hi @maddes-b, the GitHub provider for GCM Core will respect the `credential.useHttpPath` option, and store credentials against the full remote URL, if set to `true`.

If this option is set to `false` (or unset, the default), it will store credentials against only the hostname (`https://github.com`) _and_ explicit user if provided in the remote URL.

For example, with `credential.useHttpPath` set to `false/unset` the following remote URLs will use the same credentials:

```text
Credential: "git:https://github.com" (user = alice) 

   https://github.com/foo/bar
   https://github.com/contoso/widgets
   https://alice@github.com/contoso/widgets
```
```text
Credential: "git:https://bob@github.com" (user = bob)

   https://bob@github.com/foo/bar
   https://bob@github.com/example/myrepo
```

..whereas if `credential.useHttpPath` is `true` then:

```text
Credential: "git:https://github.com/foo/bar" (user = alice)

   https://github.com/foo/bar
```
```text
Credential: "git:https://github.com/contoso/widgets" (user = alice)

   https://github.com/contoso/widgets
   https://alice@github.com/contoso/widgets
```
```text
Credential: "git:https://bob@github.com/foo/bar" (user = bob)

   https://bob@github.com/foo/bar
```
```text
Credential: "git:https://bob@github.com/example/myrepo" (user = bob)

   https://bob@github.com/example/myrepo
```

Hopefully this should be as expected and consistent with your current setup with GCM for Windows. Please let me know if there are problems! 😄 

I'll keep this issue open to track enhancing multi-user documentation.

**Comment by maddes-b** [comment]
Thanks for pointing out. I thought it was a GCM for Windows setting but it actually is from [git][1] itself.

[Here][2]'s how the last version of the GCM for Windows documented it. Just recognized that they added a special note mentioning that it actually is a git setting. But they didn't mention that this can be defined for specific hosts, although doing so in their example.

I would also note in the documentation that this setting should **not** be set system-wide (`--system`) via [git-config][3], but either for the user (`--global`) or per repository (`--local`). Although that is just my opinion.

Examples:
```
git config --global credential.useHttpPath false
git config --global credential.github.com.useHttpPath true
```
```
git config --global credential.useHttpPath true
cd <working directory>
git config --local credential.remote.domain.com.useHttpPath false
```

Thanks again
Matthias

[1]: https://git-scm.com/docs/gitcredentials#_configuration_options
[2]: https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/master/Docs/Configuration.md#usehttppath
[3]: https://git-scm.com/docs/git-config#Documentation/git-config.txt---global
