### ISSUE TITLE
Failed to Login to github when I'm trying to fetch the latest 

### ISSUE THREAD

**Issue by AhmedTarekElgendy** [microsoft/Git-Credential-Manager-Core#254]
I even uninstalled git nd installed it again but same issue
this is the output:

Fetching from origin
git: 'credential-manager-core' is not a git command. See 'git --help'.
Logon failed, use ctrl+c to cancel basic credential prompt.
Error: cannot spawn /c/program files (x86)/microsoft visual studio/2019/enterprise/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
Error encountered while fetching: Failed to fetch from the remote repository. See the Output window for more details.

**Comment by mjcheetham** [comment]
Hi @AhmedTarekElgendy, are you using Git from inside of Visual Studio, either via Team Explorer/Git window, or the VS command prompt window? Or are you using Git outside of Visual Studio (Windows Command Prompt, or PowerShell)?

From the output/error snippet you posted (thanks!) it looks like something is going on in the Git configuration and settings in Visual Studio.

**Comment by mjcheetham** [comment]
Hi @AhmedTarekElgendy, in addition to the questions above, can I ask if this same issue occurs when doing a clone/push/fetch using Git from Windows Command Prompt (cmd.exe)?

Can you also confirm what (if any) version of Git for Windows you have installed? Please run `git version` from the Command Prompt. Thanks!

**Comment by AhmedTarekElgendy** [comment]
@mjcheetham sorry for the late reply I fixed it o the same day.
Thanks.
