### ISSUE TITLE
Can't find git installed in WSL

### ISSUE THREAD

**Issue by kevinji** [microsoft/Git-Credential-Manager-Core#255]
**Feature description**

Is there any way to have GCM Core look for Git installed in WSL?

I have git installed in WSL Ubuntu, but Git Credential Manager installed in Windows, as I'd like to use Windows's built-in credential store. I added git-credential-manager-core.exe as a `credential.helper` for git (per [instructions for the git-credential-manager](https://stackoverflow.com/questions/45925964/how-to-use-git-credential-store-on-wsl-ubuntu-on-windows)), but when I tried using this I got the error

```
Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
   at Microsoft.Git.CredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at Microsoft.Git.CredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem)
   at Microsoft.Git.CredentialManager.CommandContext..ctor()
   at Microsoft.Git.CredentialManager.Program.Main(String[] args)
```

Is there any way I can manually override the path for Git? Do I need to install Git on both Windows and Ubuntu? It'd be nice to avoid a second Git installation if possible.

**Comment by aaronpowell** [comment]
By the looks of it, you'll need to have Git installed on Windows as well as WSL - https://github.com/microsoft/Git-Credential-Manager-Core/blob/c38fdc2cf71e066cc54fcaf2282916f3a1749e37/src/shared/Microsoft.Git.CredentialManager/CommandContext.cs#L149

The reason (at least, from what I can gather digging in the code) is that the GUI needs to probe your git config when it runs, but since the GUI is a Windows app, and as such runs in Windows, it will look for `git.exe` to invoke the commands.

The way the app runs makes it look like there's no way which it could be overridden.

**Comment by kevinji** [comment]
Gotcha, is there a specific reason why the Linux version of git couldn’t be used instead, by calling `wsl git`? I’m not fully sure of when Windows programs can call WSL ones and vice versa.

**Comment by aaronpowell** [comment]
They can, but there'd need to be some way which the process can know that it was invoked from WSL, rather that directly from Windows, and I'm not sure if that comes through.

**Comment by kevinji** [comment]
Sounds good. Going to close this unless it's actually something you want to add support for.

**Comment by mhofman** [comment]
I would actually like to see support for this. Handle credentials on the windows side, backed by Windows Credentials Manager, but use git only in WSL 2, without any global installation in Windows.

VS Code already works pretty well that way with the remote infrastructure.

**Comment by mhofman** [comment]
I've tried to use [wslgit](https://github.com/andy-5/wslgit) and now I'm stuck at some weird stdin behavior. It seems that `git-credential-manager-core` is ignoring any stdin, either from WSL (`cat get-input | /mnt/c/path/to/git-credential-manager-core.exe get`) or even from a regular command prompt (`type get-input | C:\path\to\git-credential-manager-core.exe get`).

Any clue what might be going on?

```
22:03:16.863108 ...\Application.cs:80   trace: [RunInternalAsync] Version: 2.0.452.3248
22:03:16.867109 ...\Application.cs:81   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
22:03:16.867109 ...\Application.cs:82   trace: [RunInternalAsync] Platform: Windows (x86-64)
22:03:16.867109 ...\Application.cs:83   trace: [RunInternalAsync] AppPath: c:\Users\mhofman\AppData\Local\Programs\Git Credential Manager Core\git-credential-manager-core
22:03:16.867109 ...\Application.cs:84   trace: [RunInternalAsync] Arguments: get
22:03:16.905370 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
fatal: Missing 'protocol' input argument
```

**Comment by Robula** [comment]
I installed GCMC on Windows to authenticate git in WSL but hit this error, why would anyone install GCMC separately if it's reliant on Git being resident in Windows? You may as well just install the regular Windows git-scm!

**Comment by Mrmachine3** [comment]
When you edit the global config using `git config --global --edit`, does it contain two helper entries in the **[credential]** section? I found that my configuration included two credential.helper entries for "/usr/bin/git-credential-manager-core" and "/mnt/c/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core\/git-credential-manager-core.exe".

So to solve the error posted by the @kevinji, I removed the reference to the executable located in the "/mnt/c/" filepath.. I hope this helps solve your initial issue as well.

**Comment by DylanSpOddball** [comment]
@Robula (and anyone else trying to use GCM on WSL without installing Git on Windows): you can use the `GIT_EXEC_PATH` environment variable to point GCM to Git on WSL. Set its value to the directory where `git` is installed in WSL, then calling GCM should work from within WSL:
```
$ which git
/usr/bin/git
$ export GIT_EXEC_PATH="/usr/bin"
$ /mnt/c/Users/DylanSprague/AppData/Local/Programs/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe --version
2.0.567+3047faf390
```
