### ISSUE TITLE
Install failed when /usr/local/bin directory does not exist in macOS

### ISSUE THREAD

**Issue by bluekyu** [microsoft/Git-Credential-Manager-Core#256]
'ln' command is failed when "/usr/local/bin" directory does not exist in macOS (Apple Silicon):
```
package_script_service[1860]: ./postinstall: ln: /usr/local/bin/git-credential-manager-core: No such file or directory
```

The script was succeed after I created the directory.

**Comment by mjcheetham** [comment]
Thanks for discovering this issue, and raising the bug! 👍 

This has been fixed in #257 and will be included in the next release of GCM Core. Thanks again!
