### ISSUE TITLE
Scoped githubauthmodes is ignored when using scoped provider setting.

### ISSUE THREAD

**Issue by cliffchapmanrbx** [microsoft/Git-Credential-Manager-Core#258]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.

This command didn't work. I'm using a fresh installation of [Git for Windows 2.30.](https://github.com/git-for-windows/git/releases/tag/v2.30.0.windows.1) so whatever version is packaged in there. Their last update mentioning GCM Core mentions version  v2.0.289.48418.

**Which Git host provider are you trying to connect to?**

* GitHub
* GitHub Enterprise

### Issue version 0:

I try to clone a repo from our GitHub Enterprise server. The system opens a simple interface box requesting a username and password. It is not GitHub branded. I dismiss it and begin reading the configuration docs to see how I can get the dedicated GitHub authentication mode.

### Alternate issue 1:

I have configured my company's server in the config according to [the configuration guide](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/configuration.md) to use github authentication for our GitHub Enterprise server. Because of #235 we can't use OAuth with this system, so I have configured it to only use basic auth.

From an Admin pwsh 7 prompt: 

```
git config --global credential.github.contoso.com.provider github
git config --global credential.github.contoso.com.githubauthmodes basic
```

I then run the command `git clone https://github.contoso.com/Contoso/a-repo-name.git`

I see `fatal: Must specify at least one AuthenticationModes`, and it prompts me for a username on the CLI. I do not get the GitHub branded login box.

If I clone a repo from github.com/Contoso it works fine, I get the OAuth prompt, I go through the browser-based auth flow, and everything works perfectly. Go team 😊

Logs for this situation (cloning from GHE, not dotcom):

```
PS C:\git> git clone https://github.contoso.com/Contoso/a-repo-name.git
18:29:34.304904 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
18:29:34.306887 git.c:444               trace: built-in: git clone https://github.contoso.com/Contoso/a-repo-name.git
Cloning into 'a-repo-name'...
18:29:34.359905 run-command.c:664       trace: run_command: git remote-https origin https://github.contoso.com/Contoso/a-repo-name.git
18:29:34.384903 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
18:29:34.387870 git.c:730               trace: exec: git-remote-https origin https://github.contoso.com/Contoso/a-repo-name.git
18:29:34.387870 run-command.c:664       trace: run_command: git-remote-https origin https://github.contoso.com/Contoso/a-repo-name.git
18:29:34.420869 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
18:29:34.537903 run-command.c:664       trace: run_command: 'git credential-manager-core get'
18:29:34.733944 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
18:29:34.736868 git.c:730               trace: exec: git-credential-manager-core get
18:29:34.736868 run-command.c:664       trace: run_command: git-credential-manager-core get
18:29:34.834922 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.289-beta+22bd06dc57 (Windows, .NET Framework 4.0.30319.42000) 'get'
18:29:34.844903 ...\Command.cs:63       trace: [ExecuteAsync] Start 'get' command...
18:29:34.853871 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
18:29:34.854868 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
18:29:34.854868 ...\Command.cs:75       trace: [ExecuteAsync]   host=github.contoso.com
18:29:34.883904 ...oviderRegistry.cs:84 trace: [GetProvider] Host provider override was set id='github'
18:29:34.884905 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'GitHub' was selected.
18:29:34.887902 ...\HostProvider.cs:115 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.contoso.com account=...
18:29:34.890906 ...\HostProvider.cs:120 trace: [GetCredentialAsync] No existing credentials found.
18:29:34.890906 ...\HostProvider.cs:123 trace: [GetCredentialAsync] Creating new credential...
18:29:34.946870 ...bHostProvider.cs:197 trace: [GetSupportedAuthenticationModesAsync] https://github.contoso.com/ is GitHub Enterprise - checking for supporting authentication schemes...
18:29:34.958903 ...GitHubRestApi.cs:119 trace: [GetMetaInfoAsync] HTTP: GET https://github.contoso.com/api/v3/meta
18:29:34.968868 ...pClientFactory.cs:53 trace: [CreateClient] Creating new HTTP client instance...
18:29:35.301867 ...GitHubRestApi.cs:123 trace: [GetMetaInfoAsync] HTTP: Response 200 [OK]
18:29:35.403902 ...bHostProvider.cs:213 trace: [GetSupportedAuthenticationModesAsync] GitHub Enterprise instance has version '2.22.1' and supports authentication schemes: None
fatal: Must specify at least one AuthenticationModes
Parameter name: modes
18:29:35.473868 run-command.c:664       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://github.contoso.com':^C
PS C:\git>
```

### Alternate 2:

Git config:

```
credential.github.contoso.com.provider=github
credential.githubauthmodes=basic
```

This works as expected for cloning from github.contoso.com. On first clone I get a GitHub-branded popup window to enter my username and password (for which I use a PAT). It stores correctly, and subsequent clones do not prompt for credentials.

However, if I try to push for the first time to any of our repos on github.com/Contoso I get the same username/password prompt, instead of the OAuth prompt. It won't use oauth with github.com.

This issue is preventing me from writing up our internal documentation on how to use Git to authenticate to our internal systems.

**Comment by mjcheetham** [comment]
Hello! I think at least one of the issues here is related to #223 which was fixed in #234, but not yet released. We are not reading configuration values correctly due to case-sensitivity issues with key names.

Regarding setting of the auth modes to basic only for GHES, can I ask if you're GHES instance supports basic username/password, or has this been disabled?

The reason I ask is because by default, if you don't set the auth modes setting, for GHES we will ask the instance what auth modes it supports, and as of the currently released version, will show username/password as an option if basic user/pass is enabled on the instance.

Sadly, if user/pass has been disabled, with the current version you will get the "need at least one mode" error. In the latest code (not yet released) we've added an explicit Personal Access Token (PAT) mode which is always available for GHES (and github.com).

We hope to get this latest update out soon. Sorry for any inconvenience.

**Comment by cliffchapmanrbx** [comment]
Ahha, that issue didn't come up in my search. Yes this looks like it's the same root cause.

Our GHES system is set up to require auth with our SSO provider, Okta. I suspect this means it has 'hidden' the userpass option as it's not really supported at all.

Do you have an ETA on a release? This directly affects how I need to write our docs for our developers to follow. If the answer is "in the next week or two" it's very different than "next quarter" :)

**Comment by mjcheetham** [comment]
In the next week is the right timeframe 😄

**Comment by vtbassmatt** [comment]
@mjcheetham I'm closing this one since I assume we've shipped the fix already. Please reactivate if I'm wrong.
