### ISSUE TITLE
Simplify usage in Azure Cloud Shell

### ISSUE THREAD

**Issue by aelij** [microsoft/Git-Credential-Manager-Core#261]
**Feature description**

Azure Cloud Shell sessions are ephemeral, so setting up PGP is not a great solution. I read that git has an in-memory credential store - https://git-scm.com/docs/git-credential-cache

> The stored credentials never touch the disk, and are forgotten after a configurable timeout. The cache is accessible over a Unix domain socket, restricted to the current user by filesystem permissions.

Would it be possible to configure the credential manager to use this store?

**Comment by vtbassmatt** [comment]
@vtbassmatt to investigate whether [we're](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/linuxcredstores.md) compatible with the built-in [credential cache](https://git-scm.com/docs/git-credential-cache), and document if so.

**Comment by vtbassmatt** [comment]
Ah, after reading more about the credential cache, this isn't as trivial as I thought. Still not too bad, though:
1. Pull [this](https://github.com/microsoft/Git-Credential-Manager-Core/blob/307e9366da407f2d5b070f875f2cfc413214ddb9/src/shared/Microsoft.Git.CredentialManager/Authentication/AuthenticationBase.cs#L25-L67) out into a process invoker helper
2. Add a new option [here](https://github.com/microsoft/Git-Credential-Manager-Core/blob/66a573128898b28d46884a643eb6a446ab264562/src/shared/Microsoft.Git.CredentialManager/Interop/Linux/LinuxCredentialStore.cs) which delegates CRUD to `git credential-cache`.
