### ISSUE TITLE
Possible to have a gcmcoreuser-win.zip?

### ISSUE THREAD

**Issue by justinjbird** [microsoft/Git-Credential-Manager-Core#266]
Only exe available for user version. Will be rejected by many a firewall, is it possible to have a zip added to the assets?

**Comment by vtbassmatt** [comment]
@justinjbird the exes are installers, while the zip is only the GCM Core application files. The app itself doesn't change between the system-wide installer and the user installer, so there's nothing different to publish as a zip.

**Comment by mjcheetham** [comment]
@vtbassmatt is correct. The only differences would be where the binaries are installed to, and which `configure` command is called post install.

`configure --system` requires admin to be able to modify the system Git config. `config` does not as it modifies your current user (`--global`) config.
