### ISSUE TITLE
Crashes on M1 Mac (Rosetta)

### ISSUE THREAD

**Issue by nateroling** [microsoft/Git-Credential-Manager-Core#270]
**Which version of GCM Core are you using?**
Git Credential Manager version 2.0.318-beta+44acfafa98 (macOS, .NET Core 3.1.10)

**Which Git host provider are you trying to connect to?**
Azure DevOps

**Can you access the remote repository directly in the browser using the remote URL?**
Yes

---

**_[Azure DevOps only]_ What format is your remote URL?**
https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**
Not applicable

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

Credential manager was installed with Homebrew, inside Terminal.app which is set to "Open using Rosetta."

Git was also installed the same way — everything is Rosetta-transpiled, not ARM native.
 
**Actual behavior**

Git clone outputs `fatal: helper error (133): Unknown` and then prompts for username and password, which fails to authenticate.

A "Problem Report for Microsoft.Authentication.Helper" window pops up.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

```
12:27:29.548366 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/bin/git
12:27:29.549180 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/bin
12:27:29.549542 git.c:439               trace: built-in: git clone https://company.visualstudio.com/company/_git/repo folder
Cloning into 'folder'...
12:27:29.555998 run-command.c:663       trace: run_command: git-remote-https origin https://company.visualstudio.com/company/_git/repo
12:27:29.568691 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/libexec/git-core/git-remote-https
12:27:29.569381 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/libexec/git-core
12:27:29.817061 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
12:27:30.084592 ...er/Application.cs:69 trace: [RunInternalAsync] Git Credential Manager version 2.0.318-beta+44acfafa98 (macOS, .NET Core 3.1.10) 'get'
12:27:30.104331 ...mmands/Command.cs:63 trace: [ExecuteAsync] Start 'get' command...
12:27:30.131717 ...mmands/Command.cs:74 trace: [ExecuteAsync] Detecting host provider for input:
12:27:30.133496 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	protocol=https
12:27:30.133592 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	host=company.visualstudio.com
12:27:30.183852 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
12:27:30.186714 ...mmands/Command.cs:77 trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
12:27:30.189841 ...osHostProvider.cs:66 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://company.visualstudio.com account=...
12:27:30.210725 ...osHostProvider.cs:71 trace: [GetCredentialAsync] No existing credentials found.
12:27:30.210790 ...osHostProvider.cs:74 trace: [GetCredentialAsync] Creating new credential...
12:27:30.213631 ...sHostProvider.cs:141 trace: [GenerateCredentialAsync] Determining Microsoft Authentication Authority...
12:27:30.218280 ...eDevOpsRestApi.cs:46 trace: [GetAuthorityAsync] HTTP: HEAD https://company.visualstudio.com/
12:27:30.219592 ...pClientFactory.cs:53 trace: [CreateClient] Creating new HTTP client instance...
12:27:30.763416 ...eDevOpsRestApi.cs:49 trace: [GetAuthorityAsync] HTTP: Response code ignored.
12:27:30.763760 ...eDevOpsRestApi.cs:50 trace: [GetAuthorityAsync] Inspecting headers...
12:27:30.801950 ...eDevOpsRestApi.cs:57 trace: [GetAuthorityAsync] Found WWW-Authenticate header with Bearer authority 'https://login.microsoftonline.com/9d121530-24d9-4475-8af3-f029e6649bdf'.
12:27:30.803336 ...sHostProvider.cs:143 trace: [GenerateCredentialAsync] Authority is 'https://login.microsoftonline.com/9d121530-24d9-4475-8af3-f029e6649bdf'.
12:27:30.803351 ...sHostProvider.cs:146 trace: [GenerateCredentialAsync] Getting Azure AD access token...
12:27:30:887000 ...Mac/Source/main.m:92 trace: Running Microsoft Authentication helper for macOS
12:27:30:936000 ...e/AHAppDelegate.m:33 trace: Creating application context for authentication prompt
fatal: helper error (133): Unknown
```

**Comment by nateroling** [comment]
Here is the crash output from the Problem Reporter as well:
https://gist.github.com/nateroling/6799320938c398a5f653f7c1669a9b77

**Comment by nateroling** [comment]
Likely a dupe of #264

**Comment by aaroncrespo** [comment]
I've tried rolling back to previous working releases and those packages seem to no longer be signed or have valid pkg installs.

**Comment by aaroncrespo** [comment]
ADAL has reported that the WebKit issue is fixed with ADAL 4.0.11

Potential patch.
```
PODS:
  - ADAL (4.0.11):
    - ADAL/app-lib (= 4.0.11)
  - ADAL/app-lib (4.0.11):
    - ADAL/tokencacheheader

```

**Comment by mjcheetham** [comment]
Hello! Thanks for raising this. Please see my response for a workaround in this issue comment:

https://github.com/microsoft/Git-Credential-Manager-Core/issues/264#issuecomment-772519884

> We currently plan to remove the native macOS helper that's based on ADAL altogether as part of some other changes (to move away from Azure DevOps PATs and use AAD/MSA access tokens directly), but that's still a work-in-progress.

**Comment by vtbassmatt** [comment]
Not sure if this is precisely a dupe, but it seems to be adequately covered by the solution and workarounds in #264, so I'll close.
