### ISSUE TITLE
GCM does not remember credentials when using Azure DevOps in WSL

### ISSUE THREAD

**Issue by matt-FFFFFF** [microsoft/Git-Credential-Manager-Core#271]
**Which version of GCM Core are you using?**

Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000)

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [x] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated once and then Git Credential Manager stores my access token for reuse

Note: git in WSL configured to use Windows GCM:
```bash
git config --global credential.helper "/mnt/c/Users/mattf/AppData/Local/Programs/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe"
```

**Actual behavior**

I get a popup every time I perform a git operation on the remote.

**Logs**

```
21:39:48.174019 git.c:439               trace: built-in: git pull
21:39:48.174145 run-command.c:663       trace: run_command: git fetch --update-head-ok
21:39:48.174652 git.c:439               trace: built-in: git fetch --update-head-ok
21:39:48.174862 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://{org}@dev.azure.com/{org}/{project}/_git/{repo}
21:39:48.938912 run-command.c:663       trace: run_command: '/mnt/c/Users/mattf/AppData/Local/Programs/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe get'
21:39:55.226675 run-command.c:663       trace: run_command: '/mnt/c/Users/mattf/AppData/Local/Programs/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe store'
21:39:55.475691 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
21:39:55.476846 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
21:39:55.477343 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
21:39:55.479739 run-command.c:1616      run_processes_parallel: preparing to run up to 1 tasks
21:39:55.479757 run-command.c:1648      run_processes_parallel: done
21:39:55.479761 run-command.c:663       trace: run_command: git gc --auto
21:39:55.480226 git.c:439               trace: built-in: git gc --auto
21:39:55.480493 run-command.c:663       trace: run_command: git merge FETCH_HEAD
21:39:55.480974 git.c:439               trace: built-in: git merge FETCH_HEAD
Already up to date.
```

**Comment by matt-FFFFFF** [comment]
Ok, I think this issue was caused by this Windows Defender setting being enabled:

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-controlled-folders

I turned it off, then ran `wsl --shutdown` and the issue was fixed.

Closing

**Comment by kethahel99** [comment]
This cannot be the only solution right? What if your organization enforces this setting on Windows Defender for "ransomware protection" ? 😮

![image](https://user-images.githubusercontent.com/25621492/193362884-e3151fdc-1335-4ae2-b431-64c65057824e.png)
