### ISSUE TITLE
fatal: Authentication failed for 'https://myserver.com/DefaultCollection/' not asking for credentials

### ISSUE THREAD

**Issue by valeriob** [microsoft/Git-Credential-Manager-Core#291]
**Which version of GCM Core are you using?**
Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000)

**Which Git host provider are you trying to connect to?**
Azure DevOps Server (TFS/on-prem)

**Can you access the remote repository directly in the browser using the remote URL?**
Yes (it alwso works fine on other pcs)

**Expected behavior**
git commands on the remote should ask for credentials. Example git fetch

**Actual behavior**
any git command on the remote responds fatal: Authentication failed for 

A clear and concise description of what happens. For example: exception is thrown, UI freezes, etc.

**Logs**
$ GCM_TRACE=1 GIT_TRACE=1 git fetch
14:51:16.124984 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files (x86)/Git/mingw32/bin
14:51:16.127985 git.c:444               trace: built-in: git fetch
14:51:16.132985 run-command.c:664       trace: run_command: GIT_DIR=.git git remote-https origin https://myserver.com/DefaultCollection/BU-RSI/_git/OnRtls
14:51:16.152985 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files (x86)/Git/mingw32/libexec/git-core
14:51:16.154985 git.c:730               trace: exec: git-remote-https origin https://myserver.com/DefaultCollection/BU-RSI/_git/OnRtls
14:51:16.154985 run-command.c:664       trace: run_command: git-remote-https origin https://myserver.com/DefaultCollection/BU-RSI/_git/OnRtls
14:51:16.176985 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files (x86)/Git/mingw32/libexec/git-core
14:51:16.900347 run-command.c:664       trace: run_command: 'c:/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe get'
14:51:17.045011 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000) 'get'
14:51:17.053611 ...\Command.cs:63       trace: [ExecuteAsync] Start 'get' command...
14:51:17.062613 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
14:51:17.063612 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
14:51:17.063612 ...\Command.cs:75       trace: [ExecuteAsync]   host=myserver.com
14:51:17.167610 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
14:51:17.169611 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'Generic' was selected.
14:51:17.172611 ...\HostProvider.cs:115 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://myserver.com account=...
14:51:17.176611 ...\HostProvider.cs:120 trace: [GetCredentialAsync] No existing credentials found.
14:51:17.176611 ...\HostProvider.cs:123 trace: [GetCredentialAsync] Creating new credential...
14:51:17.278611 ...icHostProvider.cs:60 trace: [GenerateCredentialAsync] Checking host 'https://myserver.com/' for Windows Integrated Authentication...
14:51:17.281613 ...Authentication.cs:36 trace: [GetIsSupportedAsync] HTTP: HEAD https://myserver.com/
14:51:17.282612 ...pClientFactory.cs:53 trace: [CreateClient] Creating new HTTP client instance...
14:51:18.193870 ...Authentication.cs:39 trace: [GetIsSupportedAsync] HTTP: Response code ignored.
14:51:18.193870 ...Authentication.cs:41 trace: [GetIsSupportedAsync] Inspecting WWW-Authenticate headers...
14:51:18.194870 ...Authentication.cs:46 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for Negotiate
14:51:18.194870 ...Authentication.cs:51 trace: [GetIsSupportedAsync] Found WWW-Authenticate header for NTLM
14:51:18.194870 ...icHostProvider.cs:69 trace: [GenerateCredentialAsync] Host supports WIA - generating empty credential...
14:51:18.194870 ...\HostProvider.cs:125 trace: [GetCredentialAsync] Credential created.
14:51:18.195872 ...\Command.cs:81       trace: [ExecuteAsync] End 'get' command...
14:51:18.417434 run-command.c:664       trace: run_command: 'c:/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core.exe erase'
14:51:18.556975 ...\Application.cs:69   trace: [RunInternalAsync] Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000) 'erase'
14:51:18.564972 ...\Command.cs:63       trace: [ExecuteAsync] Start 'erase' command...
14:51:18.576973 ...\Command.cs:74       trace: [ExecuteAsync] Detecting host provider for input:
14:51:18.577973 ...\Command.cs:75       trace: [ExecuteAsync]   protocol=https
14:51:18.577973 ...\Command.cs:75       trace: [ExecuteAsync]   host=myserver.com
14:51:18.577973 ...\Command.cs:75       trace: [ExecuteAsync]   username=
14:51:18.577973 ...\Command.cs:75       trace: [ExecuteAsync]   password=********
14:51:18.686972 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
14:51:18.688971 ...\Command.cs:77       trace: [ExecuteAsync] Host provider 'Generic' was selected.
14:51:18.688971 ...\HostProvider.cs:162 trace: [EraseCredentialAsync] Erasing stored credential in store with service=https://myserver.com account=...
14:51:18.692971 ...\HostProvider.cs:169 trace: [EraseCredentialAsync] No credential was erased.
14:51:18.692971 ...\Command.cs:81       trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for 'https://myserver.com/DefaultCollection/BU-RSI/_git/OnRtls/'

**Comment by mjcheetham** [comment]
Hi @valeriob!

It looks like what's happening is GCM is detecting that the onprem TFS instance supports Windows Integrated Authentication (Kerberos/NTLM)..

```
14:51:18.194870 ...icHostProvider.cs:69 trace: [GenerateCredentialAsync] Host supports WIA - generating empty credential...
```

..and then telling Git to let cURL use WIA.

However, I assume that the user account you're signed-in to Windows with is _not_ the correct use for that TFS instance?

To tell GCM to not consider WIA and prompt for a username & password, please set the [following configuration](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/configuration.md#credentialallowwindowsauth):

```
git config --global credential.myserver.com.allowWindowsAuth false
```

This will disable WIA for all `myserver.com` remotes.

**Comment by valeriob** [comment]
Thank you very much, that was it !
