### ISSUE TITLE
Allow to provide Personnal Access Token though git configuration

### ISSUE THREAD

**Issue by jairbubbles** [microsoft/Git-Credential-Manager-Core#292]
Hello!

It seems it's valid to use a Personal Access Token to authenticate and I was wondering if this could be set through the git configuration (and so by the command line too with `-c`). It would be helpful in non-interactive scenario for HTTPS authentication.

For instance the setting could be called `credential.accesstoken` allowing to run command such as:

`git push -c credential.accesstoken=xxxx`

I couldn't find anything similar in https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/configuration.md#available-settings so I opened this issue to engage the discussion.

Thanks in advance!

**Comment by mjcheetham** [comment]
As you have found, the `-c` option in Git allows you to specify configuration on the command line.

You can already do what you ask for using Git's built-in configuration, without needing a new `credential.accesstoken` entry!


```sh
$ git push -c http.extraheader="Authorization: <credential-header-value>" ...
```

This will tell Git to include the extra `Authorization` header on its requests. If you have a username/password credential then pass:

```
"Authorization: Basic <base64(username:password)>"
```

..where the value in `<...>` is the base64 encoded string consisting of the username and password, separated by a `:` character.

If you have a bearer token, pass:

```
"Authorization: Bearer <TOKEN>"
```
