### ISSUE TITLE
Credentials Window does not appear for non-privileged user (504 Timeout)

### ISSUE THREAD

**Issue by sburkard** [microsoft/Git-Credential-Manager-Core#295]
**Which version of GCM Core are you using?**

Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000)
(Bundled with git version 2.30.1.windows.1)

I install Git with bundled GCM through **Scoop package manager**. So the whole **Git package is installed in my user profile and I need no admin privileges** for it.

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [X] Other - please describe

Company GitLab-Server (on premise)

**Can you access the remote repository directly in the browser using the remote URL?**

Yes.

---

**Expected behavior**

I can enter my credentials in a Windows Security dialog that appears,  I am authenticated and my Git operation completes successfully.

**Actual behavior**

It seems that **GCM-Core is unable to show the credentials window for a non-privileged user**. Instead I get two long delays and 504 Timeouts. Finally I can enter my credentials on the command line. 

New setup, first git operation against server (repository clone) with **non-privileged user**

1. execute git clone
2. git-credential-helper-selector appears and the entry "manager-core" is preselected
3. click OK
4. **nothing happens for about 90 seconds**, then I get a **HTTP 504 Gateway Timeout**
5. again, **nothing happens for about 90 seconds**, then I get **another HTTP 504 Gateway Timeout** and I can **enter my credentials on the command line** (fallback?)
6. enter credentials
7. the repository is successfully cloned and my credentials are saved in the Windows Credential Manager
 
There are two credentials, one for `gitlab.company.com` and one for `uid12345@gitlab.company.com`. I guess the two 90 second delays and following timeouts correspond to the two credential entries.

New setup, first git operation against server (repository clone) with **privileged user (local admin)**

1. execute git clone
2. git-credential-helper-selector appears and the entry "manager-core" is preselected
3. click OK
4. **Git Credential Manager Window appears immediately**
5. enter credentials
7. the repository is successfully cloned and my credentials are saved in the Windows Credential Manager

**Logs**

Git Trace log for the procedure with the non-privileged user. Notice the two delays > 1 minute in the timestamps.

PS C:\Users\uid12345> git clone https://gitlab.company.com/group/repository
14:26:18.638729 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/bin
14:26:18.638729 git.c:444               trace: built-in: git clone https://gitlab.company.com/group/repository
Cloning into 'repository'...
14:26:18.654378 run-command.c:664       trace: run_command: git remote-https origin https://gitlab.company.com/group/repository
14:26:18.669995 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core
14:26:18.669995 git.c:730               trace: exec: git-remote-https origin https://gitlab.company.com/group/repository
14:26:18.669995 run-command.c:664       trace: run_command: git-remote-https origin https://gitlab.company.com/group/repository
14:26:18.685614 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core
14:26:18.748174 run-command.c:664       trace: run_command: 'git credential-helper-selector get'
14:26:18.873112 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core
14:26:18.873112 git.c:730               trace: exec: git-credential-helper-selector get
14:26:18.873112 run-command.c:664       trace: run_command: git-credential-helper-selector get
14:27:55.430774 run-command.c:664       trace: run_command: 'git credential-manager-core get'
14:27:55.462014 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core
14:27:55.477647 git.c:730               trace: exec: git-credential-manager-core get
14:27:55.477647 run-command.c:664       trace: run_command: git-credential-manager-core get
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcmcore-tlsverify for more information.
fatal: An error occurred while sending the request.
fatal: The remote server returned an error: (504) Gateway Timeout.
14:29:10.852822 run-command.c:664       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://gitlab.company.com': uid12345
14:29:33.321590 run-command.c:664       trace: run_command: bash -c 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://uid12345@gitlab.company.com':
14:29:40.774762 run-command.c:664       trace: run_command: 'git credential-helper-selector store'
14:29:40.821601 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core
14:29:40.821601 git.c:730               trace: exec: git-credential-helper-selector store
14:29:40.821601 run-command.c:664       trace: run_command: git-credential-helper-selector store
14:29:46.337226 run-command.c:664       trace: run_command: 'git credential-manager-core store'
14:29:46.399751 exec-cmd.c:237          trace: resolved executable dir: C:/Users/uid12345/scoop/apps/git/2.30.1.windows.1/mingw64/libexec/git-core
14:29:46.399751 git.c:730               trace: exec: git-credential-manager-core store
14:29:46.399751 run-command.c:664       trace: run_command: git-credential-manager-core store
warning: redirecting to https://gitlab.company.com/group/repository.git/
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (186/186), done.
...
Successful clone

**GCM Logs**

Attached GCM.log as suggested in the comment. I anonymized the log the same way as the log above (company.com instead of real name, uid12345 instead of real uid). 

[gcm.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/6047903/gcm.log)

**Comment by mjcheetham** [comment]
Hello @sburkard can you please reproduce the issue with the `GCM_TRACE` environment variable set and include those logs too please?

```batch
SET GCM_TRACE=C:\Users\uid12345\gcm.log
```

**Comment by sburkard** [comment]
Hello @mjcheetham 
I attached the GCM log. What I noticed is the part about the proxy right before the delay. 

```
[TryCreateProxy] Created a WebProxy instance:
[TryCreateProxy] 	uri=http://www-proxy.company.com:8080/
[CreateClient] HTTP client is using the configured proxy.
```

The thing is: our GitLab server is on premise, so it is not reachable via proxy, but direct. This would explain the delay and timeout. 

The question is: where does GCM take the proxy information from? 

For Git and other tools we configure the environment variables `http_proxy`, `https_proxy` and `no_proxy`. The `company.com` domain is one of the `no_proxy` entries.

**Comment by mjcheetham** [comment]
> I attached the GCM log.

Thanks!

> What I noticed is the part about the proxy right before the delay.

Ahaa!

> The question is: where does GCM take the proxy information from?

> For Git and other tools we configure the environment variables http_proxy, https_proxy and no_proxy. The company.com domain is one of the no_proxy entries.

GCM reads proxy information from the same Git (cURL) environment variables, namely: `HTTP_PROXY`, `HTTPS_PROXY`, and `ALL_PROXY`.

_However_, we do **not** currently read or handle `NO_PROXY` entries! There is an open issue to add this: https://github.com/microsoft/Git-Credential-Manager-Core/issues/297

**Comment by sburkard** [comment]
Turned out, this is a duplicate of #297
