### ISSUE TITLE
GCMC Do Not Prompt for User Credit

### ISSUE THREAD

**Issue by galsi** [microsoft/Git-Credential-Manager-Core#304]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.
Git Credential Manager version 2.0.318-beta+44acfafa98 (Windows, .NET Framework 4.0.30319.42000)

**Which Git host provider are you trying to connect to?**

* [X ] Azure DevOps
* [X ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**
YES
From a terminal, run `git remote -v` to see your remote URL.

CMMrepo https://azdo-01/MCollection/Git/_git/CGit.CMM (fetch)
CMMrepo https://azdo-01/MCollection/Git/_git/CGit.CMM (push)
origin  https://azdo-01/MCollection/GIT/_git/CGit (fetch)
origin  https://azdo-01/MCollection/GIT/_git/CGit (push)

* [X ] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [X ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

Prompt for User & Password

**Actual behavior**
Error : fatal: Authentication failed for 'https://azdo-01/MCollection/GIT/_git/CGit/'

**Logs**
[GCMC.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/6114757/GCMC.log)

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by mjcheetham** [comment]
You are using Azure DevOps Server/TFS, which appears to be configured for Kerberos/NTLM authentication.
The logs for GCM show that we're signalling to Git that it (cURL in reality) should negotiate via Windows Authentication.

```
Checking host 'https://azdo-01/' for Windows Integrated Authentication...
..removed..
Found WWW-Authenticate header for Negotiate
Found WWW-Authenticate header for NTLM
Host supports WIA - generating empty credential...
```

If you wish to select a user other than the current Windows user, please [set the following configuration option](https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/configuration.md#credentialallowwindowsauth) to avoid detecting and using Windows Integrated Authentication (WIA); this will force a user/pass prompt:

```
git config --global credential.allowWindowsAuth false
```

This will disable WIA detection for all repositories.

To instead selectively disable WIA detection/use for a particular TFS remote, use the following command (where `azdo-01` is the TFS remote URL domain you want to stop using WIA for):

```
git config --global credential.azdo-01.allowWindowsAuth false
```

**Comment by galsi** [comment]
Thanks it is working now!!
