### ISSUE TITLE
fatal: Failed to enumerate all Git configuration entries [129] error: unknown option `show-scope'

### ISSUE THREAD

**Issue by eisber** [microsoft/Git-Credential-Manager-Core#313]
**Which version of GCM Core are you using?**

2.0.394-beta+3fc6791abf

Also: 

Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020
git version 2.25.1 (latest available on Ubuntu)

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [x] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [x] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

fatal: Failed to enumerate all Git configuration entries [129]
error: unknown option `show-scope'
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    -t, --type <>         value is given this type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)
    --expiry-date         value is an expiry date

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)
    --default <value>     with --get, use default value when missing entry

fatal: Authentication failed for

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by mjcheetham** [comment]
Hi @eisber,

Starting in GCM Core version 2.0.394, we [make use of the `--show-scope` option](https://github.com/microsoft/Git-Credential-Manager-Core/commit/b9dfb071c7685a5dd58625b16df725ac9b830cdf) on the `git config` command.

This option was [first introduced](https://github.com/git/git/commit/145d59f48233c64cb8a9262c9f1451cc7d66b530) in Git 2.26.0.

> git version 2.25.1 (latest available on Ubuntu)

I see that Ubuntu's apt-get feeds only have 2.25.x as the latest, as you mentioned.

Whilst we consider how to possibly fall-back to another method of reading Git config with the scopes, would it be possible for you to try one of the following workarounds?

- Update to the latest stable Git version, not from Ubuntu's feeds: https://git-scm.com/download/linux

> **Debian/Ubuntu**
> **For the latest stable version for your release of Debian/Ubuntu**
> `# apt-get install git`
>
> **For Ubuntu, this PPA provides the latest stable upstream Git version**
> `# add-apt-repository ppa:git-core/ppa`
> `# apt update; apt install git`

- Downgrade GCM to versions before 2.0.394

**Comment by edimitchel** [comment]
I have the same on Windows !

2.0.394-beta
Win10 version 1909
git version 2.22.0.windows.1

**Comment by wAuner** [comment]
The same problem also applies to macOS. The git that comes with the latest developer tools is version 2.24.3

**Comment by mjcheetham** [comment]
We've dropped the requirement and use of the `--show-scope` option. The next release should rectify this error.

**Comment by pmahend1** [comment]
Same issue here on Mac from yesterday. what is the work-around @mjcheetham ?

**Comment by wAuner** [comment]
@pmahend1 until a new version is released, you can grab the previous release from github and use that

**Comment by pmahend1** [comment]
@wAuner I couldnt install previous version through brew. I just installed for time being. Will install next version whenever it is released.
