### ISSUE TITLE
GCM Core not working with "Git-2.31.1-64-bit.exe"

### ISSUE THREAD

**Issue by AnFa1978** [microsoft/Git-Credential-Manager-Core#324]
**Which version of GCM Core are you using?**
From a terminal, run `git-credential-manager-core version` and paste the output.

I've installed "Git 2.31.1" for windows. After running command above I got: 
'git-credential-manager-core' is not recognized as an internal or external command, operable program or batch file.

**Which Git host provider are you trying to connect to?**
* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**
yes

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

Terminal shows following (tokens "org", "project" and "repo" are replaced):
origin  https://{org}@dev.azure.com/{org}/{project}/_git/{repo} (fetch)
origin  https://{org}@dev.azure.com/{org}/{project}/_git/{repo} (push)

**_[Azure DevOps only]_ What format is your remote URL?**

This is what I use in browser
* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [x] I only see one identity
* [ ] I checked each identity and none worked

What is account picker?

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

In all repositories when calling git fetch/pull/push/clone the error happen: 

“fatal: unable to access 'https://dev.azure.com/{org}/{project}/_git/repo{}/': Recv failure: Connection was reset”

**Logs**
15:25:12.923161 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
15:25:12.938790 git.c:447               trace: built-in: git fetch
15:25:12.970040 run-command.c:667       trace: run_command: GIT_DIR=.git git remote-https origin https://{org}@dev.azure.com/{org}/{project}/_git/{repo}
15:25:13.173070 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:25:13.173070 git.c:734               trace: exec: git-remote-https origin https://{org}@dev.azure.com/{org}/{project}/_git/{repo}
15:25:13.173070 run-command.c:667       trace: run_command: git-remote-https origin https://{org}@dev.azure.com/{org}/{project}/_git/{repo}
15:25:13.755564 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core

**Comment by AnFa1978** [comment]
Please delete issue. It was problem with environment variables on my machine

**Comment by joelsand** [comment]
@AnFa1978 what was the problem with your env variables?  I'm getting the same error on a new machine and haven't found any solution yet.  Using git 2.39.0.2
