### ISSUE TITLE
Git complains about bad input using credential.credentialType set to oauth

### ISSUE THREAD

**Issue by davehcdn** [microsoft/Git-Credential-Manager-Core#327]
Installed 2.0.394-beta+3fc6791abf on my mac using homebrew

```
$> git config -l
credential.helper=osxkeychain
credential.helper=/usr/local/share/gcm-core/git-credential-manager-core
credential.azrepospatmode=false
credential.https://dev.azure.com.usehttppath=true
credential.azrepos:org/{removed}.username={removed}

$> git config --get credential.helper
/usr/local/share/gcm-core/git-credential-manager-core
```

I can successfully do a git clone (GCMCore opens a browser window for my MFA / Authentication) however when I look in https://dev.azure.com/{removed}/_userSettings/tokens I can see that it generated a new PAT still...

I thought this should be all the configuration which I need to prevent using a PAT, reading the notes from #294

**Comment by mjcheetham** [comment]
Hi @davehcdn, thanks for the interest in GCM Core's new "PAT-less" mode for Azure Repos.

The setting to control this experimental option was renamed at some point during development, but the PR description linked still shows the old setting.

To enable PAT-less mode now, you need to run:

```shell
git config --global credential.azreposCredentialType oauth
```

https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/configuration.md#credentialazreposcredentialtype-experimental

**Comment by mjcheetham** [comment]
I've updated the release notes to point to this document that explains in more detail the different "credential/auth modes" for Azure Repos, and links to the new setting names.

https://github.com/microsoft/Git-Credential-Manager-Core/blob/master/docs/azrepos-users-and-tokens.md

**Comment by davehcdn** [comment]
@mjcheetham I tried it out and it seems to work but there are two things:

1) I can do a git clone and it pulls down the repo and I do not see a new PAT listed in my account on DevOps, so I assume the OAuth flow is working, however my command get's a very suspicious output which looks like it is echoing the OAuth token back to me?  I think if this is the token it's probably not intentional to show it like this?

```
>$ git clone https://{removed}@dev.azure.com/{Removed}/{Removed}/_git/Operations
Cloning into 'Operations'...
bad input: 3AiOiJ1c2VyX2ltcGVyc29[...]{Removed}e6CiHeJwJwef0Gw
remote: Azure Repos
remote: Found 675 objects to send. (270 ms)
Receiving objects: 100% (675/675), 198.42 KiB | 6.40 MiB/s, done.
Resolving deltas: 100% (9/9), done.
```

2) Looking at the azrepos-users-and-tokens.md you might want to update it to specify that the the UI is no longer the only way to manage Azure PAT for DevOps and the API is now public: https://devblogs.microsoft.com/devops/personal-access-token-lifecycle-apis-now-publicly-available/

**Comment by mjcheetham** [comment]
> 1. I can do a git clone and it pulls down the repo and I do not see a new PAT listed in my account on DevOps, so I assume the OAuth flow is working, however my command get's a very suspicious output which looks like it is echoing the OAuth token back to me?  I think if this is the token it's probably not intentional to show it like this?

The `bad input: <...>` line is written by Git itself, not GCM. I'm not sure why Git would feel this is bad input.

Please can you run this again with both the `GCM_TRACE` and `GIT_TRACE` environment variables set to the same absolute file path (for example: `C:\Users\<user>\gcm.log`), and then redact and post the contents on the file on this issue?

> 2. Looking at the azrepos-users-and-tokens.md you might want to update it to specify that the the UI is no longer the only way to manage Azure PAT for DevOps and the API is now public: https://devblogs.microsoft.com/devops/personal-access-token-lifecycle-apis-now-publicly-available/

I've just [updated](https://github.com/microsoft/Git-Credential-Manager-Core/commit/3e6719d8acccbbe583ffe4a53044f83e5e9b5dd5) this; thanks!

**Comment by davehcdn** [comment]
@mjcheetham does that output help at all?  Coworkers tested on windows 10 and they didn't get the echo back

**Comment by mjcheetham** [comment]
It looks like the `osxkeychain` helper might be getting involved/interleaved with the Git-GCM interaction.
In your `~/.gitconfig` file, can you see if you have the following entries? (note the blank line entry is important):

```ini
[credential]
    helper = 
    helper = /usr/local/share/gcm-core/git-credential-manager-core
    azreposCredentialType = oauth
```

**Comment by davehcdn** [comment]
Thank you @mjcheetham - the issue is now resolved.  I foolishly thought I knew better and I had removed that empty line from my git config at some point.

I have added it back and it no longer echos out the bad input.
