### ISSUE TITLE
Issue Cloning - Git Credential Manager Core

### ISSUE THREAD

**Issue by zalcorshark** [microsoft/Git-Credential-Manager-Core#330]
Hello, 

I am trying to clone a repo from Azure DevOps and Git is prompting me to use SSH instead of logging in.  I get the following error:

`'git: 'credential-git-credential-manager-core' is not a git command. See 'git --help'`

![image](https://user-images.githubusercontent.com/10156425/116251784-fe39a880-a73c-11eb-9bf1-04aa6fb40cd6.png)

I looked at previous issues [here](https://github.com/microsoft/Git-Credential-Manager-Core/issues/144).  I tried reinstalling and modifying my path variables with no luck.

git-credential-manager-core.exe exists in the `git --exec-path`

![image](https://user-images.githubusercontent.com/10156425/116251661-de09e980-a73c-11eb-974a-f72b45c793ad.png)

Any help is appreciated.  Thanks

**Comment by derrickstolee** [comment]
It appears that your config is incorrect somehow. Could you report the output of `git config --get-all credential.helper`? For example, my output is:

```ShellSession
$ git config --get-all credential.helper
manager-core

C:/Program\ Files\ \(x86\)/Git\ Credential\ Manager\ Core/git-credential-manager-core

```

**Comment by zalcorshark** [comment]
Sure - 

![image](https://user-images.githubusercontent.com/10156425/116255684-7bb2e800-a740-11eb-8c51-81ee073c420d.png)

**Comment by zalcorshark** [comment]
I ran this on another computer where git clone worked and got the following output:

```
git config --git-all credential.helper

manager-core
manager
```

**Comment by derrickstolee** [comment]
That `git-credential-manager-core` line is definitely wrong. You should be able to fix it by running `git-credential-manager-core configure`. If at is not on your `PATH`, you can see where it exists on my disk above (`C;\Program Files (x86)\Git Credential Manager Core\`) and execute it that way.

**Comment by zalcorshark** [comment]
Doesn't appear to have worked:

![image](https://user-images.githubusercontent.com/10156425/116260504-be76bf00-a744-11eb-9692-5b6f522fefc4.png)

Took a look at my /Git/etc/gitconfig and don't see any reference to git-credential-manager-core, just manager-core

```
[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[http]
	sslBackend = openssl
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[core]
	autocrlf = true
	fscache = true
	symlinks = false
[pull]
	rebase = false
[credential]
	helper = manager-core
[credential "https://dev.azure.com"]
	useHttpPath = true
[init]
	defaultBranch = master
```

**Comment by derrickstolee** [comment]
> Doesn't appear to have worked:
> 
> ![image](https://user-images.githubusercontent.com/10156425/116260504-be76bf00-a744-11eb-9692-5b6f522fefc4.png)

😢 

> Took a look at my /Git/etc/gitconfig and don't see any reference to git-credential-manager-core, just manager-core

If you run `git config --show-origin --get-all credential.helper` you will see which config file contains that problem. It might be your global one, might even be your repo-local one.

**Comment by zalcorshark** [comment]
Awesome!  After deleting my .gitconfig under my user profile this worked.  C:\Users\%Username%\.gitconfig

Thanks @derrickstolee
