### ISSUE TITLE
Help setting up GCM core on ubuntu

### ISSUE THREAD

**Issue by SelfHostedJawn** [microsoft/Git-Credential-Manager-Core#331]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.

**Which Git host provider are you trying to connect to?**

* [X ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [X ] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [X ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

I'm constantly asked for my password for the azure repo. After installed GCM core and initialized the pass credential store, I thought this should save my password/token for future git operations. Are there any step-by-step examples available? Or has anyone successfully set up GCM Core on a linux distro? Apologies if this isn't the right place, but I'm totally stumped. 

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by mjcheetham** [comment]
Hi @SelfHostedJawn,

Please can you answer a few of the following questions so I might be able to help diagnose the problem:

- What Linux distribution and version are you using?
- What version of GCM Core are you using?
- What sort of prompts are you seeing when being asked for credentials?
- Can you set the `GCM_TRACE=1` and `GIT_TRACE=1` environment variables, and try cloning/fetching _twice_ again. Include the logs on this issue (please redact any sensitive information that may be present).
- Can you run `git config --list --show-origin` and post the output here please (redact any sensitive information).

**Comment by vtbassmatt** [comment]
Without the additional info, I don't think we can action this one. Also, we've invested a lot in Linux setup. Can be reactivated if we get additional detail, but closing for now.
