### ISSUE TITLE
When checking for HTTPS authentication headers the proper path should be used

### ISSUE THREAD

**Issue by Vampire** [microsoft/Git-Credential-Manager-Core#342]
**Which version of GCM Core are you using?**

The one shipped with Git for Windows:
```
$ git credential-manager-core --version
2.0.394-beta+3fc6791abf
```

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [x] Other - please describe

Gitolite with Apache for HTTPS termination:

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

When the credentials manager is checking for authentication headers, it should do the `HEAD` request on the actual repo URL instead of only on the root URL.

**Actual behavior**

I do `git clone https://git.company.com/git/project` and the credentials manager does a `HEAD` request on `https://git.company.com/` to determine the available authentication headers. But these can be majorly different than on the subpath `https://git.company.com/git/` where the actual repository hosting is done.

**Comment by mjcheetham** [comment]
Hi @Vampire!

The problem here is that by design, Git itself only tells GCM (and all credential helpers) the protocol and hostname of the remote (i.e, `https://git.company.com`).

In order to get told the full remote URL, you need to configure Git to do so:

https://git-scm.com/docs/gitcredentials/#Documentation/gitcredentials.txt-useHttpPath

As a result, GCM will be told to store credentials against the entire remote URL (not just the hostname).

**Comment by Vampire** [comment]
Ah, right, I forgot about that and didn't know the actual option, thanks for telling me.

**Comment by mjcheetham** [comment]
No problem! 👍
