### ISSUE TITLE
Homebrew install/upgrade fails with latest release

### ISSUE THREAD

**Issue by aaroncrespo** [microsoft/Git-Credential-Manager-Core#351]
Looks like the brewfile is targeting a beta release that may not exist. 

This is not the first time a GCM release has had incorrect homebrew artifacts. Is it possible to verify these as part of your release process? My build and provisioning system assumes that `brew upgrade/install` will work hands off so every time this happens we have to develop workarounds.

`$ brew upgrade git-credential-manager-core`
Logs:
```
==> Upgrading 1 outdated package:
microsoft/git/git-credential-manager-core 2.0.394.50751 -> 2.0.452.3248
==> Upgrading git-credential-manager-core
==> Downloading https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.452-beta/gcmcore-osx-2.0.452.3248.pkg

curl: (22) The requested URL returned error: 404
==> Purging files for version 2.0.452.3248 of Cask git-credential-manager-core
Error: microsoft/git/git-credential-manager-core: Download failed on Cask 'git-credential-manager-core' with message: Download failed: https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.452-beta/gcmcore-osx-2.0.452.3248.pkg

```

**Comment by derrickstolee** [comment]
@mjcheetham this might be related to the change to drop `-beta` from the release definition. I see it is still in the homebrew release URL.

**Comment by penagymsft** [comment]
Do you have a sense for a timeline for the fix? We have some team members blocked by it at the moment.

**Comment by derrickstolee** [comment]
I hopefully fixed the cask. Please try again, @penagymsft.

**Comment by penagymsft** [comment]
Seems to be working. Thanks for the fast response, @derrickstolee.
