### ISSUE TITLE
After configuring: 'credential-git-credential-manager-core' is not a git command

### ISSUE THREAD

**Issue by BrianL-STCU** [microsoft/Git-Credential-Manager-Core#352]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.

```
git-credential-manager-core : The term 'git-credential-manager-core' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
```

(In my "Apps & Features", the installed version is 2.0.452.3248; I'm using Microsoft Windows 10 Pro 64-bit 10.0.19042.)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [X] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

✔ Yes, git was authenticated fine before I installed GCMC.

From a terminal, run `git remote -v` to see your remote URL.

```
origin  https://github.com/$orgname/$reponame.git (fetch)
origin  https://github.com/$username/$reponame.git (push)
```

👉 (This is not a public repo.)

* [X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

A clear and concise description of what happens. For example: exception is thrown, UI freezes, etc.

After installing GCMC, and running `git credential-manager-core configure` and reopening PowerShell, trying to do a pull in a repo fails.

```
git: 'credential-git-credential-manager-core' is not a git command. See 'git --help'.
Username for 'https://github.com': ████████████
Password for 'https://████████████@github.com':
git: 'credential-git-credential-manager-core' is not a git command. See 'git --help'.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/███████████████████████.git/'
```

After running `git credential-manager-core unconfigure`, git works again.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by connelhooley** [comment]
I had the same issue, I ran the following commands and noticed that I had different global and system settings:

```
git config --system credential.helper
manager-core

git config --global credential.helper
git-credential-manager-core
```

So I looked at my `~/.gitconfig` file in my home folder:

```
[user]
	name = My Name
	email = my@email.com
[core]
	editor = \"C:\\Users\\username\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait
[credential]
	helper = 
	helper = git-credential-manager-core
	helper = manager-core
```

I had 3 helper settings in the the credential section, so I replaced it with:

```
[user]
	name = My Name
	email = my@email.com
[core]
	editor = \"C:\\Users\\username\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait
[credential]
	helper = git-credential-manager-core
```

And it seems to be working again for me. Just thought I'd share just in-case it helped.

**Comment by BrianL-STCU** [comment]
That seems like it fixed it for me, too, @connelhooley . Thanks!

I also looked at the system gitconfig, and that needs the helper pointed to the full path of GCMC, even if the path is in the `%PATH%`, which seems to be what `git credential-manager-core configure` does, so I guess don't mess with it. :)

```ini
[credential]
	helper = C:/Program\\ Files\\ \\(x86\\)/Git\\ Credential\\ Manager\\ Core/git-credential-manager-core
```

**Comment by BrianL-STCU** [comment]
Well, it worked yesterday, but today the error is back.

**Comment by mjcheetham** [comment]
Hi @BrianL-STCU,

I am confused by this entry in your `~/.gitconfig`! I'm not sure where this would or could have come from 🤔 

```ini
	helper = git-credential-manager-core
```

> git-credential-manager-core : The term 'git-credential-manager-core' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.

Can you instead try the following: `git credential-manager-core --version` (note the space between `git` and `credential`).

Can you also check if you have any standalone installations of GCM Core? If you look in **Settings > Apps & Features** do you see any entries for GCM Core? If so, what version(s)?

What version of Git for Windows do you have installed? `git --version`

**Comment by BrianL-STCU** [comment]
Running `git credential-manager-core --version` returns `2.0.394-beta+3fc6791abf`

In Apps & Features, I have **Git Credential Manager Core 2.0.452.3248** installed.

Git reports `git version 2.31.1.windows.1` as its version.

**Comment by Narretz** [comment]
@mjcheetham

What is the helper supposed to be name `manager-core` or `credential-manager-core`? I also have this in my config, but I'm not really sure how it happened. I think it was after  `git credential-manager-core configure`

**Comment by mjcheetham** [comment]
On Windows you shouldn't need to install GCMC standalone, but should use the version that is included with Git for Windows.

Git for Windows specifies the helper as `manager-core` in the `--system` Git configuration. The GCMC bundled with Git for Windows is included on the `%PATH%` that `git.exe` uses.

_Aside: there are multiple `git.exe` executables in Git for Windows, and one is a 'wrapper' for the internal `git.exe` that does things like configure the `%PATH%` to add extra entries._

The standalone versions of GCMC on Windows that you can download from the releases page here on GitHub will attempt to override the bundled GCMC by setting the global or system configuration (depending on [which installer version you use](https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/README.md#windows)) by adding an "empty" `credential.helper` entry, _then_ specify the full path to the standalone GCMC executable. For example:

```ini
[credential]
    # this blank entry makes sure the bundled GCMC version with Git for Windows is overridden
    helper =
    helper = C:/Program\\ Files\\ \\(x86\\)/Git\\ Credential\\ Manager\\ Core/git-credential-manager-core.exe
```

We cannot just add the standalone GCMC installations to the `%PATH%` as use the `manager-core` config value because git.exe resolves to the bundled GCMC version first in all instances.

**Comment by BrianL-STCU** [comment]
I think the main reason I ended up installing the latest standalone GCMC was because GitHub kept complaining loudly and frequently about my authentication method without clearly specifying that they expect everyone to switch to token-based auth instead of passwords, and so I assumed that I needed to update the `credential.helper`.

**Comment by mjcheetham** [comment]
Closing this issue as I believe the configuration problems have been resolved? Please reopen if this is not the case.

**Comment by austinschrader** [comment]
I'm having the same error, haven't installed a standalone GCMC and do not see a resolution here.
