### ISSUE TITLE
Failed to create PAT: FailedToReadTenantPolicy

### ISSUE THREAD

**Issue by jrburek** [microsoft/Git-Credential-Manager-Core#355]
**Which version of GCM Core are you using?**

2.0.452+b00c5acad3

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [x] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [x] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

Performing an initial `git clone` on a repository. Authentication should succeed and the repository should clone successfully.

**Actual behavior**

"fatal: Failed to create PAT: FailedToReadTenantPolicy" is logged to the command line and authentication fails. From the logs, a HTTP 400 is received in response to `CreatePersonalAccessTokenAsync`. I'm using git-credential-manager on two other computers successfully (though they both have cached tokens at the moment and have not needed to request a new one yet).

**Logs**

[git.redacted.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/6541649/git.redacted.log)

**Comment by jrburek** [comment]
FWIW, I tried cloning the repo to debug and when I ran through the debugger it prompted for KeyChain access which it did not do before. It also received a success this time and updated the credentials in the KeyChain. Now when I run through the command-line it successfully pulls the cached token and works.

**Comment by mjcheetham** [comment]
Hi @jrburek,

> FailedToReadTenantPolicy

That error message comes back from the Azure DevOps server.. so I'm not sure how or what that would mean.

> Now when I run through the command-line it successfully pulls the cached token and works.

Perhaps this was a transient issue with the server at the time? That's all I can think... 🤔

**Comment by jrburek** [comment]
It did seem like the Keychain access prompt appeared before that service request was sent which might have been a difference between the two scenarios but I wasn't actually paying close enough attention to say for sure. If that doesn't ring any bells though feel free to close as transient. I can re-open if I ever see it again.

**Comment by mjcheetham** [comment]
Hi @jrburek, I'll close this issue as a transient issue, but please come back if this happens again. Thanks!
