### ISSUE TITLE
Github authentication does not persist and is not used for git operations with GCM globally set as credential.helper

### ISSUE THREAD

**Issue by aaroncrespo** [microsoft/Git-Credential-Manager-Core#365]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.

```
$ git-credential-manager-core version
'version' was not matched. Did you mean '--version'?
Required command was not provided.
Unrecognized command or argument 'version'
$ git-credential-manager-core --version
2.0.474+95a180ab30
```

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ X] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [ X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

* `carthage` issues a git command  I _think_ its something similar to `git clone https://github.com/CocoaLumberjack/CocoaLumberjack.git` OR its a git authenticated `.tar` fetch.
* The GitHub OAuth prompt appears
* Auth flow is continued and completed in the browser
* When complete git does not progress appears stuck in auth
* Trying the command again restarts the auth prompt
* After removing the global GCM helper setting from .gitconfig the git operation continues using the configured ssh/osxkeychain helper

**Logs**

From a previous GCM command I have:
```
[credential]
	helper =
	helper = /usr/local/share/gcm-core/git-credential-manager-core
	msauthHelper =
```
Which I think takes precedent even if I have
```
[credential "github.com"]
    user = aaroncrespo
    helper = osxkeychain
```
And Carthage uses https:// clones that never succeed. (GitHub Oath prompt appears, but the credential is not persisted so after auth, https git operations continue to fail)

**Comment by mjcheetham** [comment]
Hi @aaroncrespo,

Please can you run Carthage again but with the `GCM_TRACE` environment variable set to an absolute file path like `/tmp/gcm.log` and upload the resulting log?

If the auth is succeeding on the first attempt but not being persisted, it may be because Carthage is not calling the `git credential` command correctly. Callers doing a `git credential fill` (to get a credential from the configured helper) should follow up with either a `git credential approve` (if the creds are good) or `git credential reject` (if the creds are bad).

**Comment by vtbassmatt** [comment]
Without the traces, I don't see how we can action this one. We can reactivate if we get those traces.

**Comment by aaroncrespo** [comment]
My project has since migrated away from Carthage for the affected git repo's, or I found work arounds.
