### ISSUE TITLE
running sudo dpkg -i on the .deb in the download page produces a .dll file.

### ISSUE THREAD

**Issue by mxndtaylor** [microsoft/Git-Credential-Manager-Core#368]
**Which version of GCM Core are you using?**
2.0.474+95a180ab30

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

Given:

I run these commands on WSL2 inside windows terminal:

    wget https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.474/gcmcore-linux_amd64.2.0.474.41365.deb
    sudo dpkg -i gcmcore-linux_amd64.2.0.474.41365.deb
    cd <git-initialized-directory-with-remote>

When I run:

    git <cmd-needing-authentication-with-remote>

Then I expect that:

`gcmcore` runs `git-credential-manager-core get` and fills the credentials in for me.

OR  

`gcmcore` has no credentials stored and I enter them manually.  
Then it runs `git-credential-manager-core store` to store the credentials for next time.

**Actual behavior**

After running:

    git <cmd-needing-authentication-with-remote>

I instead get this as output:

    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core get: 1: /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core: not found
    Username for 'https://github.com': 

After entering my credentials:

    Username for 'https://github.com': <gh-username>
    Password for 'https://<gh-username>@github.com':

I then get:

    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core store: 1: /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core: not found

So I tried:

    ls /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core*

And found:

    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core.deps.json
    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core.dll
    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core.runtimeconfig.json

So it looks like the `.deb` package installed a `.ddl` file. 

**Logs**

After running `git push origin main`, I get this:

    18:21:09.000880 git.c:439               trace: built-in: git push origin main
    18:21:09.001204 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/<gh-username>/<repo-name>/
    18:21:09.138497 run-command.c:663       trace: run_command: '/var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core get'
    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core get: 1: /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core: not found
    Username for 'https://github.com': <gh-username>
    Password for 'https://<gh-username>@github.com':
    18:21:22.014503 run-command.c:663       trace: run_command: '/var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core store'
    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core store: 1: /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core: not found
    Everything up-to-date

**Comment by mxndtaylor** [comment]
If I run:

    mv /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core.dll /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core

Then the logs look like this instead:

    18:33:38.937195 git.c:439               trace: built-in: git push origin main
    18:33:38.937580 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://github.com/<gh-username>/<repo-name>/
    18:33:39.079125 run-command.c:663       trace: run_command: '/var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core get'
    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core get: 1: /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core: Permission denied
    Username for 'https://github.com': <gh-username>
    Password for 'https://<gh-username>@github.com':
    18:33:49.942030 run-command.c:663       trace: run_command: '/var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core store'
    /var/tmp/.net/<sys-username>/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core store: 1: /var/tmp/.net/mxt/git-credential-manager-core/unqypyc0.awl/git-credential-manager-core: Permission denied
    Everything up-to-date

So if I run:

    sudo git push origin main

I get:

    Username for 'https://github.com': <gh-username>
    Password for 'https://<gh-username>@github.com':
    Everything up-to-date

But when I re-run:

    sudo git push origin main

I have to reenter my password, so it still doesn't work.

**Comment by vtbassmatt** [comment]
@mxdntaylor does this still repro on [the latest GCM Core](https://github.com/microsoft/Git-Credential-Manager-Core/releases)? We had some packaging issues but _think_ we have them under control.

**Comment by mjcheetham** [comment]
Closing this issue as no-response. Please re-open if this is still a problem.

**Comment by mxndtaylor** [comment]
Sorry for the late response. No, this is not reproducible for me anymore because GitHub no longer supports password authentication, and I'm not on any other git hosting service. 

Also, I can't seem to find any *.dll file anywhere in my system after using the same commands I was above:

    wget https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.474/gcmcore-linux_amd64.2.0.474.41365.deb
    sudo dpkg -i gcmcore-linux_amd64.2.0.474.41365.deb

So, I believe this has been resolved? Even for the version I was trying to use, but I could be incorrect about that, as I can't _really_ test it without creating an account with some git host that still accepts password authentication.
