### ISSUE TITLE
Add a `git-askpass` executable to handle Git "askpass" prompts

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#385]
Add an askpass utility [like in Git Credential Manager for Windows](https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/master/Cli/Askpass/Program.cs) to handle GUI prompts for RSA thumbprint authenticity and key passphrases.

This is an important step so that Git for Windows can stop bundling the GCM for Windows binaries, without breaking existing users of `git-askpass.exe`

**Comment by dscho** [comment]
Git for Windows just merged a PR that builds its own `git-askpass.exe`. So I think this ticket can be closed.

**Comment by mjcheetham** [comment]
This one @dscho? https://github.com/git-for-windows/build-extra/commit/da9ba5d86be2c99089a571e73d1d62317bac8393

Sounds good! I'll close this.

**Comment by dscho** [comment]
> 
> 
> This one @dscho? [git-for-windows/build-extra@da9ba5d](https://github.com/git-for-windows/build-extra/commit/da9ba5d86be2c99089a571e73d1d62317bac8393)

Yes!

> Sounds good! I'll close this.

👍
