### ISSUE TITLE
I can independently call git-credential-manager-core.exe through cmd in the windows？

### ISSUE THREAD

**Issue by xiaofuhub** [microsoft/Git-Credential-Manager-Core#395]
I want to bypass the git tool and use git-credential-manager-core.exe directly to allow users to access github.com, I don’t know whether to provide related APIs for external programs to call

**Comment by mjcheetham** [comment]
You can call GCM in two different ways:

1. Via `git-credential`:

As long as the Git configuration has GCM set as the `credential.helper`, then you can invoke GCM using the standard Git command. You can call `git-credential fill` and pipe over a URL (`url=https://example.com`) to ask GCM for a credential. Make sure to follow up the `fill` command with either an `approve` or `reject` command afterwards.

Please refer to the [`git-credential` instructions](https://git-scm.com/docs/git-credential) on full usage.

2. Calling `git-credential-manager-core.exe` directly:

You can call GCM directly by invoking the `git-credential-manager-core.exe` process with one of the standard Git credential helper commands (`get`, `store`, `erase`) and pipe the correct information over standard input.

For example:

```batch
> C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core.exe get
protocol=https
host=example.com


```

Please refer to the official [Git credential helper documentation](https://git-scm.com/docs/gitcredentials#_custom_helpers) for correct usage.
