### ISSUE TITLE
Command to list configuration values and precedence

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#407]
**Feature description**

With the addition of platform-specific enterprise configuration values (#404) it might be a good idea to provide a way to list all of the configuration values that GCM knows about and which values/defaults are stored in there.

This might be in the form of a `gcm config` command (that also passes though to `git config`) or as part of a `gcm diagnose` diagnostic command.

**Comment by vtbassmatt** [comment]
@mjcheetham as we discussed - now that we have the `diagnose` command, maybe we include a copy of the .gitconfig files as optional riders in the output?

**Comment by mjcheetham** [comment]
We are actually already dumping out all the Git configuration entries in the current diagnostics!

https://github.com/microsoft/Git-Credential-Manager-Core/blob/c8e70d905faae0773b0f310fe32f811c9991f62c/src/shared/Microsoft.Git.CredentialManager/Diagnostics/GitDiagnostic.cs#L32-L40
