### ISSUE TITLE
Git-Credential-Manager hangs on literally everything

### ISSUE THREAD

**Issue by Alpheron** [microsoft/Git-Credential-Manager-Core#448]
When running `git-credential-manager-core` and trying to store information, it hangs and does not even show the GUI window to enter a Personal Access Token.

`❯ GCM_TRACE=1 git-credential-manager-core store
13:29:45.956644 ...er/Application.cs:80 trace: [RunInternalAsync] Version: 2.0.498.54650
13:29:45.979387 ...er/Application.cs:81 trace: [RunInternalAsync] Runtime: .NET 5.0.6
13:29:45.979482 ...er/Application.cs:82 trace: [RunInternalAsync] Platform: macOS (x86-64)
13:29:45.979551 ...er/Application.cs:83 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
13:29:45.979601 ...er/Application.cs:84 trace: [RunInternalAsync] Arguments: store
13:29:46.036726 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'store' command...`

And there it just proceeds to hang and does not do anything, is there a particular fix for this?

**Comment by mjcheetham** [comment]
From the limited trace output you provided, this is expected from the `store` command. GCM is waiting for more required information to be passed over standard input, specifically the `protocol` and `host` fields. See more [here](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-codestorecode).

Are you running `git-credential-manager-core store` directly or interacting with `git` via commands like `push` or `fetch`?

**Comment by Alpheron** [comment]
I have tried both methods actually. That stack trace I have provided was from running `git-credential-manager-core store` directly from command line but also from running other git commands such as `git push` and `git pull`.

**Comment by mjcheetham** [comment]
Can you try running a `git push` with the `GCM_TRACE=1` _**and**_ `GIT_TRACE=1` environment variables set, and include that trace output please? I'd like to see what Git is doing when talking to GCM.

To test the basic user/pass prompting.. please can you also try running the following from a terminal, and see if you are shown a prompt?

```shell
printf "protocol=https\nhost=example.com\n\n" | git-credential-manager-core get
```

**Comment by Alpheron** [comment]
It seems that the user/pass prompting from the terminal works with the statement but here is the log from a simple test commit I had created. My Personal Access Token is for some reason stored when I did not even set anything. When trying to get the Personal Access Token that was set, it still hangs.

```
12:08:46.697634 git.c:455               trace: built-in: git push
12:08:46.698289 run-command.c:666       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/Alpheron/Pressure-Based-Tumor-Detection.git
12:08:46.705799 git.c:743               trace: exec: git-remote-https origin https://github.com/Alpheron/Pressure-Based-Tumor-Detection.git
12:08:46.706338 run-command.c:666       trace: run_command: git-remote-https origin https://github.com/Alpheron/Pressure-Based-Tumor-Detection.git
12:08:46.942405 run-command.c:666       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
12:08:47.076264 ...er/Application.cs:80 trace: [RunInternalAsync] Version: 2.0.498.54650
12:08:47.096747 ...er/Application.cs:81 trace: [RunInternalAsync] Runtime: .NET 5.0.6
12:08:47.096785 ...er/Application.cs:82 trace: [RunInternalAsync] Platform: macOS (x86-64)
12:08:47.096886 ...er/Application.cs:83 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
12:08:47.096931 ...er/Application.cs:84 trace: [RunInternalAsync] Arguments: get
12:08:47.153272 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
12:08:47.161997 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
12:08:47.163065 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	protocol=https
12:08:47.163101 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	host=github.com
12:08:47.195806 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
12:08:47.197896 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
12:08:47.199035 ...GitCommandBase.cs:52 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
12:08:47.201465 .../HostProvider.cs:128 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
12:08:47.233541 .../HostProvider.cs:142 trace: [GetCredentialAsync] Existing credential found.
12:08:47.234213 ...GitCommandBase.cs:56 trace: [ExecuteAsync] End 'get' command...
12:08:47.429804 run-command.c:666       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core store'
12:08:47.565110 ...er/Application.cs:80 trace: [RunInternalAsync] Version: 2.0.498.54650
12:08:47.577792 ...er/Application.cs:81 trace: [RunInternalAsync] Runtime: .NET 5.0.6
12:08:47.577825 ...er/Application.cs:82 trace: [RunInternalAsync] Platform: macOS (x86-64)
12:08:47.577913 ...er/Application.cs:83 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
12:08:47.577955 ...er/Application.cs:84 trace: [RunInternalAsync] Arguments: store
12:08:47.634942 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'store' command...
12:08:47.643246 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
12:08:47.644442 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	protocol=https
12:08:47.644463 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	host=github.com
12:08:47.644469 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	username=Alpheron
12:08:47.644474 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	password=********
12:08:47.675445 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
12:08:47.677721 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
12:08:47.678875 ...GitCommandBase.cs:52 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
12:08:47.680193 .../HostProvider.cs:162 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=Alpheron...
12:08:47.719818 .../HostProvider.cs:164 trace: [StoreCredentialAsync] Credential was successfully stored.
12:08:47.719894 ...GitCommandBase.cs:56 trace: [ExecuteAsync] End 'store' command...
12:08:47.731334 run-command.c:666       trace: run_command: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/Alpheron/Pressure-Based-Tumor-Detection.git/ --stdin
12:08:47.738889 git.c:455               trace: built-in: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/Alpheron/Pressure-Based-Tumor-Detection.git/ --stdin
12:08:47.740779 run-command.c:666       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
12:08:47.747703 git.c:455               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 280 bytes | 280.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Alpheron/PressureTumorAI.git
To https://github.com/Alpheron/Pressure-Based-Tumor-Detection.git
   ac1abca..43face8  main -> main
```

Here is the log when trying to run the `git-credential-manager-core get` command:

```
12:12:23.279910 ...er/Application.cs:80 trace: [RunInternalAsync] Version: 2.0.498.54650
12:12:23.297854 ...er/Application.cs:81 trace: [RunInternalAsync] Runtime: .NET 5.0.6
12:12:23.297932 ...er/Application.cs:82 trace: [RunInternalAsync] Platform: macOS (x86-64)
12:12:23.298130 ...er/Application.cs:83 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager-core
12:12:23.298207 ...er/Application.cs:84 trace: [RunInternalAsync] Arguments: get
12:12:23.353411 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
```
I can type in the username and whatnot using the standard input but it seems that nothing is happening. When using a different version of the `git-credential-manager-core` I had seen a small GUI window pop up in order to authenticate the credentials, but now it is nowhere to be seen.

**Comment by vtbassmatt** [comment]
👋 Hi @Alpheron -- it looks like everything is working? In the traces above:

1. The `git push` trace shows a working, end-to-end flow
2. The `git-credential-manager-core get` trace shows GCM waiting to be piped additional details over `stdin` (as Git itself would do)

If I've missed something, can you clarify your intent? Maybe you're trying to re-use the token that GCM stored but someplace else -- if that's the case, you have to run a line like the `printf` example that @mjcheetham pointed you to [above](https://github.com/microsoft/Git-Credential-Manager-Core/issues/448#issuecomment-918353688).

**Comment by Alpheron** [comment]
Hello,
After using the git push/pull commands on VSCode, the GUI interface for entering the PAT was opened allowing me to enter the PAT and everything is working as normal now. Thank you all for the help!
