### ISSUE TITLE
GCM Core WAM picker should be modal

### ISSUE THREAD

**Issue by maliksahil** [microsoft/Git-Credential-Manager-Core#454]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core --version` and paste the output.

2.0.498.54650

**Which Git host provider are you trying to connect to?**

* [ x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [ x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ x] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

This is a UX issue as described in the actual behavior section below.

**Actual behavior**

A clear and concise description of what happens. For example: exception is thrown, UI freezes, etc.

The cred prompt dialog isn’t launching modal, even though the CLI is blocked on it. E.g. I can Alt-Tab away from the command window and then lose the dialog (and note further that the dialog itself doesn’t show up in the Alt-Tab list). Once I minimize everything, I can find the WAM account picker dialog again.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by mjcheetham** [comment]
@maliksahil, there is a limitation here with how Windows handles terminal/consoles.

We (GCM) cannot resolve the handle to the command prompt window that has launched us. I know @bgavrilMS has looked at some problems with CLI tools and WAM before, and found there are several problems with Window ordering and handle ownership that are "by design" in Windows.

> E.g. I can Alt-Tab away from the command window

You have to be careful here.. what if I'm running in Windows Terminal, with multiple shells/tabs open? Should I be blocked on switching to another tab if one has launched a cred prompt?

**Comment by mjcheetham** [comment]
@maliksahil I'd recommend you open an issue on the MSAL repo in this instance: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

This is not something GCM can fix or change the behaviour.
