### ISSUE TITLE
Release binaries for linux-arm and linux-arm64

### ISSUE THREAD

**Issue by hickford** [microsoft/Git-Credential-Manager-Core#466]
Hi. Please [release binaries](https://github.com/microsoft/Git-Credential-Manager-Core/releases) for [linux-arm and linux-arm64](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids). These would be super useful for use on computers such as Raspberry Pi.

**Comment by hickford** [comment]
After working around a package restore issue #467, I was able to build for linux-arm `dotnet publish -r linux-arm -c Release --self-contained true -p:PublishSingleFile=true --framework net5.0`. Tested on Raspberry Pi 3. So far works as expected.

**Comment by Stos40** [comment]
This is how you're hacking me?

**Comment by vtbassmatt** [comment]
👋 hello, thanks for the feedback, and I see that you've gotten it to work 🎉 . Right now we don't have the resources to officially support ARM platforms. Support is considered [best-effort](https://github.com/microsoft/Git-Credential-Manager-Core#current-status) and we aren't planning to release packages. That could change if enough folks are interested, and we're definitely willing to investigate bugs you find.
