### ISSUE TITLE
WAM account picker should be parented to the console window

### ISSUE THREAD

**Issue by bgavrilMS** [microsoft/Git-Credential-Manager-Core#469]
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core --version` and paste the output.
GCM 2.0.498 on Win 10

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [x] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

Repro steps: 

1. Enable WAM authentication
2. Type a command that makes the account picker pops up 

**Expected behavior**

The account picker should be parented to the console window

**Actual behavior**

The account picker is parented to the desktop, and sometimes the account picker is not visible because it is under other applications.

**Solution**

```csharp

// 1. Get the window handle of the console window
[DllImport("kernel32.dll")]
static extern IntPtr GetConsoleWindow();

// 2. Pass it into MSAL

IntPtr consoleWindowHandle = GetConsoleWindow();
Func<IntPtr> consoleWindowHandleProvider = () => consoleWindowHandle;

builder = PublicClientApplicationBuilder.Create("client_id")
      .WithParentActivityOrWindow(consoleWindowHandleProvider)
```

**Comment by mjcheetham** [comment]
After an investigation in to the use of the `GetConsoleWindow` API, we have concluded that it is not possible to achieve the correct window parenting in all cases.

The `GetConsoleWindow` API is now deprecated, and part of the "old/legacy" Windows Console APIs. The window handle returned is valid only in cases that GCM was started from a command-line application connected to a `conhost.exe` console host. (For example, when you run the `cmd.exe` or `powershell.exe` shells directly.)

With the introduction of the [Pseudo Console (ConPTY) support in Windows](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/), the way command-line applications, terminals and console hosts work is more UNIX-like.

As a result, calling the `GetConsoleWindow` API when using the now championed [Windows Terminal](https://github.com/microsoft/terminal) terminal application results in a "fake" or off-screen console window handle. Any parented MSAL/WAM window appears at the default screen location `(0,0)`, and is still in the background relative to the actual terminal application window.

@bgavrilMS and I investigated alternatives to this that would potentially work in all circumstances. One possible avenue was to instead use the parent process main window handle. In the case being hosted in `conhost.exe` this worked – the parent process is the shell (e.g. `cmd.exe`) that has a main window handle that corresponds to the `conhost.exe` window.

However, the parent process (the shell; e.g. `powershell.exe` or `cmd.exe`) when hosted in Windows Terminal/using a ConPTY compatible terminal has no window handle.

One final avenue that may work is to traverse up the process tree, looking for the first/nearest process that has a non-zero window handle. In the `conhost.exe` scenario the parent to GCM would be the shell (e.g. `cmd.exe`), and that has the correct window handle, as before. In the Windows Terminal example, the parent process to GCM is the shell (e.g. `cmd.exe`) without a window handle, but _the shell parent_ is then the `WindowsTerminal.exe` process, that does have a main window handle.

**`conhost` Process Tree**
```text
cmd.exe                              (valid handle)
├── conhost.exe
└── git-credential-manager-core.exe  (*)↑
```

**Windows Terminal Process Tree**
```text
WindowsTerminal.exe                   (valid handle)
├── OpenConsole.exe
└── cmd.exe                           (invalid handle)↑
    └── git-credential-manager-core.exe  (*)↑
```

Of course one downside here is that parenting a modal dialog (such as WAM's account picker) to the entire terminal main window means that all interaction with the terminal is blocked, including other tabs!

Such process tree walking logic should probably not live in each consumer of MSAL, and should be handled inside of MSAL directly.
