### ISSUE TITLE
Documentation Update regarding Git Credential Core vs. Git Credential Windows

### ISSUE THREAD

**Issue by robcamer** [microsoft/Git-Credential-Manager-Core#485]
The readme.md should be updated to note that if you install the Git Tools for Windows, it has a new option to install Git Credential Core with Git tools available at this link:  https://git-scm.com/download/win.

**Comment by mjcheetham** [comment]
Thanks for the suggestion! We've added a bit about getting GCM Core as part of Git for Windows.
