### ISSUE TITLE
gcmcore-linux package missing dependency

### ISSUE THREAD

**Issue by cloudqq** [microsoft/Git-Credential-Manager-Core#506]
**Which version of GCM Core are you using?**

Download linux deb from this link below.

https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.567/gcmcore-linux_amd64.2.0.567.18224.deb

When run the git push, error occured. missing package should be packed in the deb.

And I also download the gz package, and found two so lib.

After copy these two so files to /usr/local/share/gcm-core, then it works.

Pls help to fix this package issue.

$ ls -lah
total 248M
drwxr-xr-x 2 1001 docker 4.0K Oct 28 11:35 .
drwxr-xr-x 9 root root   4.0K Oct 28 10:34 ..
-rwxr-xr-x 1 1001 docker  89M Oct 11 23:00 Atlassian.Bitbucket.UI
-rwxr-xr-x 1 1001 docker  63M Oct 11 23:00 git-credential-manager-core
-rwxr-xr-x 1 1001 docker  89M Oct 11 23:00 GitHub.UI
-rwxr-xr-x 1 root root   1.1M Oct 28 11:35 libHarfBuzzSharp.so
-rwxr-xr-x 1 root root   8.2M Oct 28 11:35 libSkiaSharp.so

$ tar tvf gcmcore-linux_amd64.2.0.567.18224.tar.gz 
-rwxr-xr-x vsts/docker 92302349 2021-10-11 23:00 Atlassian.Bitbucket.UI
-rwxr-xr-x vsts/docker 65383226 2021-10-11 23:00 git-credential-manager-core
-rwxr-xr-x vsts/docker 92355389 2021-10-11 23:00 GitHub.UI
-rwxr-xr-x vsts/docker  1086704 2020-09-11 12:53 libHarfBuzzSharp.so
-rwxr-xr-x vsts/docker  8541744 2020-09-11 12:53 libSkiaSharp.so
-rwxr-xr-x vsts/docker     2602 2021-10-11 22:59 NOTICE

 $env GCM_CREDENTIAL_STORE=gpg git push origin master 
    Error:
      An assembly specified in the application dependencies manifest (GitHub.UI.deps.json) was not found:
	package: 'HarfBuzzSharp.NativeAssets.Linux', version: '2.6.1.7'
	path: 'runtimes/linux-x64/native/libHarfBuzzSharp.so'
    fatal: helper error (140): Unknown
    Username for 'https://github.

  $ dpkg -L gcmcore
    /.
    /usr
    /usr/local
    /usr/local/bin
    /usr/local/share
    /usr/local/share/gcm-core
    /usr/local/share/gcm-core/Atlassian.Bitbucket.UI
    /usr/local/share/gcm-core/GitHub.UI
    /usr/local/share/gcm-core/git-credential-manager-core
    /usr/local/bin/Atlassian.Bitbucket.UI
    /usr/local/bin/GitHub.UI
    /usr/local/bin/git-credential-manager-core

From a terminal, run `git-credential-manager-core --version` and paste the output.

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

A clear and concise description of what happens. For example: exception is thrown, UI freezes, etc.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

**Comment by almog-co** [comment]
I am having the exact same issue. How can I fix it?

**Comment by MariaGuilarte** [comment]
What should i do? I just re-downloaded the .deb and reinstalled but didn't change anything. I'm a newbie linux mint user

**Comment by mjcheetham** [comment]
@almog-co, @MariaGuilarte the changes to fix this problem have been merged to the default branch but not yet released.
The problem of missing files will be fixed in the next release.

**Comment by dhirschfeld** [comment]
I've just run into this.

It might be an idea to at least edit the [release notes](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.567) with a warning saying the deb package is broken.

It appears that we have to install the *pre*-release version to avoid this bug?

**Comment by dhirschfeld** [comment]
Looks liek there's a workaround in https://github.com/GitCredentialManager/git-credential-manager/issues/528#issuecomment-968766281. I'll give that a go...
