### ISSUE TITLE
Perform host provider auto-detection only once per host

### ISSUE THREAD

**Issue by gpakosz** [microsoft/Git-Credential-Manager-Core#507]
This issue is a follow up on https://github.com/microsoft/Git-Credential-Manager-Core/issues/492#issuecomment-947491034

Can the credential manager remember auto-detection results?
With the current implementation, we pay this auto-detection tax every time we `git fetch` even though the Windows' credentials manager has proper authentication information available.

In terms of implementation, maybe the credential manager could do the equivalent of
```
$ git config credential.example.com.provider <result of auto-detection>
```

Thanks

**Comment by mjcheetham** [comment]
Thanks for this issue! We've implemented this functionality pretty much as described, and it will be included in the next release of GCM! Thanks again 😁

**Comment by gpakosz** [comment]
Hey @mjcheetham 👋

Sorry for the late message. I forgot to thank you for implementing this 🙏
