### ISSUE TITLE
gcmcore package not available in microsoft repos anymore

### ISSUE THREAD

**Issue by a-zich** [microsoft/Git-Credential-Manager-Core#524]
Hi everyone,

until like a week ago, gcmcore was also provided in the microsoft repositories for Ubuntu.

Now https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/g/gcmcore/ as well as https://packages.microsoft.com/ubuntu/21.04/prod/pool/main/g/gcmcore/ are empty.

It might be a consequence of some downloading problems last week. I needed some retries to download the deb file.

Or is this intention? That packages should not be provided anymore.

**Comment by ldennington** [comment]
Hi @a-zich -

Sorry for the inconvenience on this. We are working on migrating GCM Core out of the `microsoft` org and removing all Microsoft-related components of the product. Part of this included removing the packages from the Microsoft repositories.  We may explore releasing to other repositories in the future, but for now we recommend installing the latest `.deb` package or tarball from the releases page [as detailed in the latest `README`](https://github.com/microsoft/Git-Credential-Manager-Core#ubuntudebian-distributions).
