### ISSUE TITLE
GitHub.UI fails on Pop! OS 21.04 (basically Ubuntu 21.04) due to HarfBuzz version mismatch

### ISSUE THREAD

**Issue by danielfdickinson** [microsoft/Git-Credential-Manager-Core#528]
Sorry for not doing the full bug report -- I resolved my issue by downgrading to https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.474 and no longer have the latest version (2.0.567) which has the issue, installed.

This issue that occurs is that when attempting to push to github.com on Pop! OS 21.04 (= Ubuntu 21.04) with 2.0.567 the following error is thrown.

```text
Error:
  An assembly specified in the application dependencies manifest (GitHub.UI.deps.json) was not found:
    package: 'HarfBuzzSharp.NativeAssets.Linux', version: '2.6.1.7'
    path: 'runtimes/linux-x64/native/libHarfBuzzSharp.so'
fatal: helper error (140): Unknown
```
If one instead installs 20.0.474 and GitHub Desktop using apt then the browser OAuth is correctly opened (when using the secretservice credentialStore).

**Which version of GCM Core are you using?**

Release GCM 2.0.567 for amd64 linux (.deb package)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [X] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [X] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [X] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [X] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

Explained above

**Logs**

Not particularly necessary in this case. It's an obvious library version issue (the ``GitHub.UI`` binary is built for a particular version of libHarfBuzzSharp which is older than the version on Ubuntu 21.04 and derivatives).

**Comment by lokarithm** [comment]
Same bug occurs on my machine that running Linux Mint 20.2

**Comment by mjcheetham** [comment]
Hello! This is a known issue with the Debian package we released for 2.0.567: #506

The .deb package was missing some native dependencies in this release. The fix has been applied and will be included in the next release of GCM Core.

You can also workaround the problem in 2.0.567 by downloading the [tarball `gcmcore-linux_amd64.2.0.567.18224.tar.gz`](https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.567/gcmcore-linux_amd64.2.0.567.18224.tar.gz) from the [releases page](https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.567), and extracting the `libSkiaSharp.so` and `libHarfBuzzSharp.so` files to `/usr/local/share/gcm-core`.

**Comment by BertF1966** [comment]
A bit of instruction on how and where to install for linux and github newbies would be great please.

**Comment by lokarithm** [comment]
> A bit of instruction on how and where to install for linux and github newbies would be great please.

Check out this link:
https://github.com/GitCredentialManager/git-credential-manager

Keep in mind that
