### ISSUE TITLE
Latest beta version broke my git credential system. 

### ISSUE THREAD

**Issue by kunjee17** [microsoft/Git-Credential-Manager-Core#58]
Hi, 

I am using traditional git with gitlab, github, bitbucket. From those only github is having ssh access. I do have multiple accounts on other sites so I normally go with https access. More flexible for me. It never gives me any issue. 

But recently I needed to clone site from azure dev ops. And that was not working with traditional git. So, I follow up the issue and tried the new beta version. It work with Azure dev ops but it did broke with every other git provider. I did mention this in [issue](https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux/issues/90) . 

cc/ @mjcheetham

**Comment by mjcheetham** [comment]
Hello @kunjee17,

Have you tried a more recent release of GCM Core? Do you still experience similar issues?

https://github.com/microsoft/Git-Credential-Manager-Core/releases/latest

Thanks!

**Comment by mjcheetham** [comment]
Closing due to lack of response. Hopefully the issues experiences are fixed in the latest releases.
If not please open a new issue.
