### ISSUE TITLE
Install via Homebrew

### ISSUE THREAD

**Issue by carlowahlstedt** [microsoft/Git-Credential-Manager-Core#81]
**Feature description**

Homebrew is a really nice way to manage installing and updating applications on macOS. Is there any way to be able to install this that way?

**Comment by jrbriggs** [comment]
We haven't yet set up distribution through Homebrew, but it's very much on our radar. We'll use this issue to track.

Thanks for the interest!

**Comment by aaroncrespo** [comment]
We'd probably switch to this project over the old java based solution. However, no homebrew is a bit of a blocker since thats how we provision machines on my team. 

I threw together a rough (untested) cask file. Cask because this is currently distributed via `pkgutil`:


```ruby
cask 'Git-Credential-Manager-Core' do
  version '2.0.87build15236'
  sha256 '843b2eae147e784789246c043b7f7a54b85139d9'
  
  # strip build\d+ for the path
  # replace build with . for the pkg name
  url "https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v#{version.sub(%r{build\d+}, '')}-beta/gcmcore-osx-#{version.sub(%r{build}, '.')}.pkg"

  name 'Git Credential Manager Core'

  homepage 'https://github.com/Microsoft/Git-Credential-Manager-Core'

  pkg "gcmcore-osx-#{version.sub(%r{build}, '.')}.pkg"

  uninstall script:  {
                       executable: 'uninstall.sh',
                       sudo:       true,
                     },
            pkgutil: 'com.microsoft.GitCredentialManager'
end
```

see https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md for why version|build is modified as it is.

**Comment by aaroncrespo** [comment]
Any movement on this? I would love to move our systems over and away from a java dependency.

**Comment by mjcheetham** [comment]
Hello all! Just an update that we've been working on getting GCM Core delivered via Homebrew.
You can try using our new Tap and installing the Cask from there:

```sh
brew tap microsoft/git
brew cask install git-credential-manager-core
```

Please file any issues if you encounter them :)
Thanks especially to @aaroncrespo ❤️
