### ISSUE TITLE
Ability to paste in password

### ISSUE THREAD

**Issue by paulirwin** [microsoft/Git-Credential-Manager-Core#82]
**Feature description**

With GCM Core on macOS, you cannot paste in a password into the password field. This makes it very difficult to use with password managers.

**Comment by mjcheetham** [comment]
@paulirwin are you unable to paste into a GitHub/basic auth prompt, like this:

> ![image](https://user-images.githubusercontent.com/5658207/69718538-86f68400-1106-11ea-9e0c-9a60f08541be.png)

..or a Microsoft auth prompt, like this:

> ![image](https://user-images.githubusercontent.com/5658207/69718560-94137300-1106-11ea-8909-e68c97062f7d.png)

?

**Comment by paulirwin** [comment]
The Microsoft auth prompt web view.

**Comment by mjcheetham** [comment]
Thanks for reporting this @paulirwin! The next release will include the fix to allow copy/paste/cut etc.
