### ISSUE TITLE
Sign MacOS releases or update Mac Signing certs for Catalina

### ISSUE THREAD

**Issue by aaroncrespo** [microsoft/Git-Credential-Manager-Core#84]
The current preview cannot be used on Mac because it is not signed correctly. (at least for Catalina)

**Comment by mjcheetham** [comment]
Thanks for reporting this @aaroncrespo.

The binaries & installer are codesigned but not notarised, which is causing the problem on Catalina where it is now mandatory.

**Comment by mjcheetham** [comment]
@aaroncrespo please can you try the latest release? This version should now be both signed and notarized.

https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.87-beta
