### ISSUE TITLE
Setting to disable interactive/modal auth

### ISSUE THREAD

**Issue by jrbriggs** [microsoft/Git-Credential-Manager-Core#90]
GCM for Windows has an important setting for using Git on headless environments:

[GCM_INTERACTIVE](https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/master/Docs/Environment.md#gcm_interactive) and [credential.interactive](https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/master/Docs/Configuration.md#interactive)

These are important to bring over so we don't break headless scenarios, as well as being able to forcibly disable interactive auth in certain scenarios.

**Comment by Chowdhury3320** [comment]
GCM INTERACTIVE and credential. Interactive
