### ISSUE TITLE
Use GitHub web-flow instead of authorizations API

### ISSUE THREAD

**Issue by jcansdale** [microsoft/Git-Credential-Manager-Core#97]
The GitHub authorizations API that is being used at the moment and will be going away.

- Deprecating OAuth Authorization API
https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

All applications will need to update to use the Web application flow instead.

- Authorizing OAuth Apps - Web application flow
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow

There are a few important differences to consider when using Oauth tokens instead of PATs. They are very similar, but PATs are special in a few ways.

### Users can generate PATs with access to their organization's repositories without the organization needing to authorize the app

We need to make sure the app is authorized so that organization owned repositories can be accessed.

### PATs implicitly include the `workflow` scope which allows them to push GitHub Actions workflows

An Oauth app will need to explicitly request the `workflow` scope.

### PATs can do SAML SSO authentication on demand (e.g. when user tries to clone a SAML SSO protected repository)

Users will need to do the SAML SSO when they authenticate using the web-flow. If they don't do this, they will need an easy way to re-authenticate and do the SAML SSO dance.

### Any number of PATs can be created with the same set of Oauth scopes

Oauth apps are limited to 10 tokens per user per set of scopes. If a user authenticates on many machines, their older tokens will expire. We need to ensure that this is handled gracefully.

### PATs can easily be generated for a specific named user

If the user is already logged into GitHub with their browser, it can be painful to authenticate for a different user. They might need a way to specify which user they want to initiate the web-flow for (I believe it is possible to pass a username to the web-flow URL).

### A PAT can be passed directly into the current UI as a password

Might users sometimes want to use a PAT that has been generated manually? Say they want to use different scopes or the PAT has been given to them by someone else.

**Comment by mjcheetham** [comment]
Thanks for creating this issue @jcansdale! I have been experimenting with the OAuth2/web-flow for GitHub in some local branches.

**Comment by jcansdale** [comment]
No problem! I hope the experimenting is going well. 😄

**Comment by mjcheetham** [comment]
@jcansdale I've a PR which updates the auth and UI stacks for GitHub #101 
GitHub.com is _not_ yet identified as OAuth-only until we've nailed down the app whitelisting, and GHES does not offer the OAuth option until that's been rolled out to a known GHES version. You can override these things with the `$GCM_GITHUB_AUTHMODES` environment variable (see the updated /docs from that PR).
