### ISSUE TITLE
`--help` should include a link to the docs

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/Git-Credential-Manager-Core#98]
**Feature description**

```shell
$ git credential-manager-core --help
No manual entry for git-credential-manager-core
```

Either a real `man` page or at least link to the online documentation.

**Comment by vtbassmatt** [comment]
@mjcheetham if it's easy to add a link to repo-based docs, let's do it soon. Otherwise, let's close. Generating manpages hasn't become a priority in the year since this was opened.

**Comment by mjcheetham** [comment]
Cutting this issue.

**Comment by bradykelly** [comment]
This is just one of the reasons I would give this plugin a negative rating on GitHub. Setting it up is painful and the plugin documentation hopeless.

**Comment by Gregg-Casey** [comment]
after getting this error and reading these responses, I am just going to uninstall this utility.
